var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6-impl","es3");
$jscomp.polyfill("Number.isInteger",function(a){return a?a:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6-impl","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6-impl","es3");
(function(a){if("function"===typeof define&&define.amd)define(a);else if("object"===typeof exports)module.exports=a();else{var b=window.Cookies,c=window.Cookies=a();c.noConflict=function(){window.Cookies=b;return c}}})(function(){function a(){for(var a=0,b={};a<arguments.length;a++){var e=arguments[a],f;for(f in e)b[f]=e[f]}return b}function b(c){function d(b,f,g){var e;if("undefined"!==typeof document){if(1<arguments.length){g=a({path:"/"},d.defaults,g);if("number"===typeof g.expires){var k=new Date;
k.setMilliseconds(k.getMilliseconds()+864E5*g.expires);g.expires=k}try{e=JSON.stringify(f),/^[\{\[]/.test(e)&&(f=e)}catch(p){}f=c.write?c.write(f,b):encodeURIComponent(String(f)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent);b=encodeURIComponent(String(b));b=b.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);b=b.replace(/[\(\)]/g,escape);return document.cookie=[b,"=",f,g.expires&&"; expires="+g.expires.toUTCString(),g.path&&"; path="+g.path,g.domain&&
"; domain="+g.domain,g.secure?"; secure":""].join("")}b||(e={});for(var k=document.cookie?document.cookie.split("; "):[],q=/(%[0-9A-Z]{2})+/g,n=0;n<k.length;n++){var r=k[n].split("="),h=r.slice(1).join("=");'"'===h.charAt(0)&&(h=h.slice(1,-1));try{var m=r[0].replace(q,decodeURIComponent),h=c.read?c.read(h,m):c(h,m)||h.replace(q,decodeURIComponent);if(this.json)try{h=JSON.parse(h)}catch(p){}if(b===m){e=h;break}b||(e[m]=h)}catch(p){}}return e}}d.set=d;d.get=function(a){return d(a)};d.getJSON=function(){return d.apply({json:!0},
[].slice.call(arguments))};d.defaults={};d.remove=function(b,c){d(b,"",a(c,{expires:-1}))};d.withConverter=b;return d}return b(function(){})});var IS_DEBUG=!0,MAX_STRINGS_STYLE=12,MAX_STRINGS_NUMBER=18,MIN_STRINGS_NUMBER=3,MAX_ITEMS_NUMBER=5,ITEMS_ID_BASE="menuItem",FRETS_NUMBER=24,DEFAULT_METR_BEATS=4,DEFAULT_METR_BEAT_VAL=4,DEFAULT_METR_VOLUME=50,DEFAULT_METR_TEMPO=120,MIN_BEATS=1,MAX_BEATS=16,MIN_BEAT_VAL=1,MAX_BEAT_VAL=32,MIN_TEMPO=40,MAX_TEMPO=320,TEMPO_OPTIONS_STEP=5,SECOND_CLICK_FREQ=880,FIRST_CLICK_FREQ=1480,DEFAULT_SCALE_OPTIONS_EXPIRE_DAYS=30,DEFAULT_NOTES_SHOW_PATTERN=[!0,!0,!0,!0,!0,!0,!0,!0,!0,!0,!0,!0],DEFAULT_TRIADS_SHOW_PATTERN=
[!0,!1,!0,!1,!0,!1,!1,!1,!1,!1,!1,!1],NOTES="C C# D D# E F F# G G# A A# B".split(" "),DEFAULT_SCALE_SEMITONES=[2,2,1,2,2,2,1],DEFAULT_STRING_TUNES="E B G D A E B F# C# G# D# A#".split(" "),DEFAULT_SCALE_NOTES="CDEFGAB".split(""),SCALES={major:[2,2,1,2,2,2,1],ionian:[2,2,1,2,2,2,1],aeolian:[2,1,2,2,1,2,2],minor:[2,1,2,2,1,2,2],harmonic_min:[2,1,2,2,1,3,1],chromatic:[1,1,1,1,1,1,1,1,1,1,1,1],dorian:[2,1,2,2,2,1,2],phrygian:[1,2,2,2,1,2,2],lydian:[2,2,2,1,2,2,1],myxolydian:[2,2,1,2,2,1,2],locrian:[1,
2,2,1,2,2,2],melodic_min:[2,1,2,2,2,2,1],alt_dom:[1,2,1,2,2,2,2],sup_locrian:[1,2,1,2,2,2,2],dim_whole_tone:[1,2,1,2,2,2,2],alt_scale:[1,2,1,2,2,2,2],blues_min_hex:[3,2,1,1,3,2],blues_pent:[3,2,1,4,2],blues:[3,2,1,1,3,1,1],major_pent:[2,2,3,2,3],suspended_pent:[2,3,2,3,2],dorian_pent:[2,3,2,3,2],phrygian_pent:[3,2,3,2,2],myxolydian_pent:[2,3,2,2,3],aeolian_pent:[3,2,2,3,2],minor_pent:[3,2,2,3,2],major_beb:[2,2,1,2,1,1,2,1],minor_beb:[2,1,1,1,2,2,1,2],dom_beb:[2,2,1,2,2,1,1,1],dorian_beb:[2,1,1,1,
2,2,1,2],whole_tone:[2,2,2,2,2,2],whole_half_tone:[2,1,2,1,2,1,2,1],half_whole_tone:[1,2,1,2,1,2,1,2],dim:[2,1,2,1,2,1,2,1],dom_dim:[1,2,1,2,1,2,1,2],symm_dim:[1,2,1,2,1,2,1,2],spanish:[1,2,2,2,1,2,2],acoustic:[2,2,2,1,2,1,2],bartok:[2,2,2,1,2,1,2]},CHORDS={min_triad:["1","b3","5"],min_6:["1","b3","5","6"],min_b6:["1","b3","5","b6"],min_7:["1","b3","5","b7"],min_9:["1","b3","5","b7","b9"],min_11:"1 b3 5 b7 (9) 11".split(" "),min_13:"1 b3 5 b7 (9) (11) 13".split(" "),min_maj_7:["1","b3","5","7"],min_7_f5:["1",
"b3","b5","b7"],full_dim:["1","b3","b5","bb7"],maj_triad:["1","3","5"],maj_6:["1","3","5","6"],maj_7:["1","3","5","7"],maj_9:["1","3","5","7","9"],maj_11:"1 3 5 7 (9) 11".split(" "),maj_13:"1 3 5 7 (9) (11) 13".split(" "),sus_2:["1","2","5"],sus_4:["1","4","5"],dom_7:["1","3","5","b7"],dom_9:["1","3","5","b7","b9"],dom_11:"1 3 5 b7 (9) 11".split(" "),dom_13:"1 3 5 b7 (9) (11) 13".split(" "),dim_triad:["1","b3","b5"],aug_triad:["1","3","#5"]},TUNINGS={standart_e:"E B G D A E B F# C# G# D# A#".split(" "),
standart_e_bass:["G","D","A","E","B"],standart_e_bass_6:"CGDAEB".split(""),drop_d_6:"E B G D A D B F# C# G# D# A#".split(" "),drop_a_7:"E B G D A E A F# C# G# D# A#".split(" "),drop_e_8:"E B G D A E B E C# G# D# A#".split(" ")},CUSTOM_TUNING_VALUE="custom",COLOR_SCHEMES_CLASSES=["day","night"],SCALES_TYPE="scales",CHORDS_TYPE="chords",BG_BLOCK_CLASS="bg_block",ITEM_CLASS="item_block",ITEM_CONTENT_CLASS="item_content",ITEM_HEAD_CLASS="item_head",ITEM_HEAD_SELECT_CLASS="item_head_select",ITEM_OPTIONS_BLOCK=
"item_options_block",STRING_NUMBER_CLASS="strings_number",SCALE_SELECT_CLASS="scale_select",NECK_BLOCK_CLASS="neck_block",FRETBOARD_CLASS="fretboard",HOR_FRET_CLASS="fret_hor",NULL_VER_FRET_CLASS="fret_null",VER_FRET_CLASS="fret_ver",VER_FRET_INNER_CLASS="fret_ver_inner",FRET_HOVER_CLASS="fret_ver_hover",FRET_HOVER_ACTIVE_CENTER_CLASS="fret_ver_hover_active_center",FRET_HOVER_ACTIVE_START_CLASS="fret_ver_hover_active_start",FRET_HOVER_ACTIVE_END_CLASS="fret_ver_hover_active_end",NOTE_CLASS="note",
NORMAL_NOTE_CLASS="normal_note",HIGHLIGHTED_NOTE_CLASS="highlighted_note",TRANSPARENT_NOTE_CLASS="transparent_note",HIDDEN_NOTE_CLASS="hidden_note",STRINGS_OPTIONS_BLOCK_CLASS="strings_options_block",STRING_TUNE_BLOCK_CLASS="string_tune",STRING_TUNE_SELECT_CLASS="string_tune_select",LEFT_ARROW_CLASS="left_arrow",RIGHT_ARROW_CLASS="right_arrow",TUNING_OPTIONS_CLASS="tuning_options",HALF_STEP_BLOCK_CLASS="half_step_block",HALF_STEP_SELECT_CLASS="half_step_select",TUNING_SELECT_CLASS="tuning_select",
ROOT_NOTE_CLASS="root_note",SELECTED_TEXT_CLASS="selected_text",SCALE_NOTES_BLOCK_CLASS="scale_notes_and_semitones_block",SCALE_NOTES_CLASS="scale_notes",SCALE_NOTE_CLASS="scale_note",SCALE_NOTE_TEXT_CLASS="scale_note_text",ADD_STRING_BTN_CLASS="add_string",DEL_STRING_BTN_CLASS="delete_string",CLOSE_BTN_CLASS="close_btn",SET_DEFAULT_BTN_CLASS="set_default_btn",TRIADS_CHECKBOX_CLASS="triads_checkbox",TRIADS_CHECKBOX_EMPTY_CLASS="triads_checkbox_empty",LH_TOGGLE_BLOCK_CLASS="lh_toggle_block",TOGGLE_CHECKBOX_CLASS=
"toggle_checkbox",LH_TOGGLE_CLASS="lh_toggle",RH_TOGGLE_CLASS="rh_toggle",TOGGLE_SLIDER_CLASS="toggle_checkbox_slider",SLIDER_LH_CLASS="slider_lh",SLIDER_RH_CLASS="slider_rh",LH_CLASS="lh",TRANSPARENT_BLOCK_CLASS="transparent_block",METRONOME_DISABLED_ID="metronome_disabled_block",ADD_NEW_ITEM_BTN_ID="add_new_item_btn",METR_PLAY_BTN_ID="metronome_play_btn",METR_STOP_BTN_ID="metronome_stop_btn",METR_VOLUME_RANGE_ID="metronome_volume_range",METR_TEMPO_RANGE_ID="metronome_tempo_range",METR_TEMPO_OPTIONS_ID=
"tempos",METR_TEMPO_INPUT_ID="metronome_tempo_input",METR_TEMPO_LEFT_ARROW_ID="metronome_tempo_left_arrow",METR_TEMPO_RIGHT_ARROW_ID="metronome_tempo_right_arrow",METR_BEATS_SELECT_ID="metronome_beats_select",METR_BEATS_LEFT_ARROW_ID="metronome_beats_left_arrow",METR_BEATS_RIGHT_ARROW_ID="metronome_beats_right_arrow",METR_BEAT_VAL_SELECT_ID="metronome_beat_val_select",METR_BEAT_VAL_LEFT_ARROW_ID="metronome_beat_val_left_arrow",METR_BEAT_VAL_RIGHT_ARROW_ID="metronome_beat_val_right_arrow",METR_BEAT_VIS_BLOCK_ID=
"metronome_beat_vis_block",METR_BEAT_VIS_NUMBER_ID="metronome_beat_number_vis",METR_BEAT_VIS_POINTER_ID="metronome_pointer_block",METR_BEAT_VIS_POINTER_FIRST_CLASS="metronome_pointer_first",METR_BEAT_VIS_POINTER_OTHER_CLASS="metronome_pointer_other",METR_FIRST_BEAT_VIS_NUMBER_CLASS="metronome_first_beat_number_vis",COMMON_SETTINGS_BTN_ID="common_settings_btn",COMMON_SETTINGS_BLOCK_ID="settings_block",COMMON_SETTINGS_BLOCK_HIDE_CLASS="settings_block_hide",COMMON_SETTINGS_BLOCK_CLOSE_BTN_ID="settings_close_btn",
COMMON_SETTINGS_BLOCK_NIGHT_COLOR_BTN_ID="color_scheme_switch_night_btn",COMMON_SETTINGS_BLOCK_DAY_COLOR_BTN_ID="color_scheme_switch_day_btn",QUERY_PARAMS_READ_ERROR_MSG="GET parameter cannot be decoded",METR_DATALIST_OPTION_TMPL=doT.template($("#metronome_datalist_option_tmpl").html()),ITEM_BASE_BLOCK_TMPL=doT.template($("#item_base_tmpl").html()),STRINGS_BTNS_BLOCK_TMPL=doT.template($("#strings_btns_tmpl").html()),LH_TOGGLE_BLOCK_TMPL=doT.template($("#lh_toggle_tmpl").html()),NECK_BLOCK_TMPL=doT.template($("#neck_tmpl").html()),
TUNING_OPTIONS_BLOCK_TMPL=doT.template($("#tuning_options_tmpl").html()),SCALES_SELECT_BLOCK_TMPL=doT.template($("#scales_select_tmpl").html()),SCALES_OPTIONS_BLOCK_TMPL=doT.template($("#scales_options_tmpl").html()),SCALE_NOTES_TMPL=doT.template($("#scale_notes_tmpl").html()),STRING_VER_FRET_TMPL=doT.template($("#string_ver_fret_tmpl").html()),STRING_FRET_TMPL=doT.template($("#string_hor_fret_tmpl").html()),STRING_FRET_MARK_TMPL=doT.template($("#fretboard_single_mark").html()),STRING_DOUBLE_FRET_MARK_TMPL=
doT.template($("#fretboard_double_mark").html()),FRET_DOT_TMPL=doT.template($("#fret_dot_tmpl").html()),FRET_DOUBLE_DOT_TMPL=doT.template($("#fret_double_dot_tmpl").html()),STRING_TUNE_BLOCK_TMPL=doT.template($("#string_tune_block_tmpl").html());function Note(a){this._noteName=this.defaultNoteName();this._isArgReceived(a)&&this.set(a)}Note.prototype._IS_DEBUG=IS_DEBUG;Note.prototype._ALL_NOTES="C C# D D# E F F# G G# A A# B".split(" ");Note.prototype._FLAT_SYMBOL="b";Note.prototype._SHARP_SYMBOL="#";Note.prototype._isArgReceived=function(a){return void 0!==a};Note.prototype._validateSemiTonesArg=function(a){return!this._isArgReceived(a)||"number"!=typeof a||isNaN(a)?(this._IS_DEBUG&&console.error("Invalid semitones number argument"),0):a};
Note.prototype._noteNameArg=function(a){return this._isArgReceived(a)?a:this._noteName};Note.prototype._isValid=function(a){return this._isValidNormal(a)||this._isValidFlat(a)||this._isAltSharp(a)};Note.prototype._isValidNormal=function(a){return-1<this._ALL_NOTES.indexOf(a)};Note.prototype._isValidFlat=function(a){return a[a.length-1]===this._FLAT_SYMBOL&&this._isValidNormal(a.slice(0,-1))};Note.prototype._isValidSharp=function(a){return a[a.length-1]===this._SHARP_SYMBOL&&this._isValidNormal(a)};
Note.prototype._isAltSharp=function(a){return a[a.length-1]===this._SHARP_SYMBOL&&this._isValidNormal(a.slice(0,-1))&&!this._isValidNormal(a)};Note.prototype._higher=function(){this._noteName=this.higherName(this._noteName);return this};Note.prototype._lower=function(){this._noteName=this.lowerName(this._noteName);return this};Note.prototype._higherST=function(a){this._noteName=this.higherSTName(a,this._noteName);return this};
Note.prototype._lowerST=function(a){this._noteName=this.lowerSTName(a,this._noteName);return this};Note.prototype.set=function(a){this._noteName=this.validateNoteName(a);return this};Note.prototype.setName=Note.prototype.set;Note.prototype.getName=function(){return this._noteName};Note.prototype.getCopy=function(){var a=this.getName();return new Note(a)};Note.prototype.defaultNoteName=function(){return this._ALL_NOTES[0]};Note.prototype.getAllNotes=function(){return this._ALL_NOTES.slice()};
Note.prototype.isValid=function(a){if(this._isValid(a))return!0;this._IS_DEBUG&&console.error("Invalid note name: "+a);return!1};Note.prototype.isValidNormal=function(a){if(this._isValidNormal(a))return!0;this._IS_DEBUG&&console.error("Invalid note normal name: "+a);return!1};Note.prototype.isValidFlat=function(a){if(this._isValidFlat(a))return!0;this._IS_DEBUG&&console.error("Invalid flat note name: "+a);return!1};
Note.prototype.isValidSharp=function(a){if(this._isValidSharp(a))return!0;this._IS_DEBUG&&console.error("Invalid sharp note name: "+a);return!1};Note.prototype.isAltSharp=function(a){if(this._isAltSharp(a))return!0;this._IS_DEBUG&&console.error("Invalid alternative sharp note name: "+a);return!1};
Note.prototype.validateNoteName=function(a){var b=this.defaultNoteName();if("string"!==typeof a)return this._IS_DEBUG&&console.error("Note name must be a String"),b;this.isValid(a)&&(this._isValidNormal(a)?b=a:this._isValidFlat(a)?b=this.flatToNormal(a):this._isAltSharp(a)&&(b=this.sharpToNormal(a)));return b};Note.prototype.flatToNormal=function(a){a=this._noteNameArg(a);var b=this.defaultNoteName();this.isValidFlat(a)&&(b=this.lowerName(a.slice(0,-1)));return b};
Note.prototype.sharpToFlat=function(a){a=this._noteNameArg(a);var b=this.defaultNoteName();this.isValidSharp(a)&&(b=this.higherName(a),b+=this._FLAT_SYMBOL);return b};Note.prototype.sharpToNormal=function(a){a=this._noteNameArg(a);var b=this.defaultNoteName();this.isAltSharp(a)&&(b=this.higherName(a.slice(0,-1)));return b};Note.prototype.higherName=function(a){a=this.validateNoteName(this._noteNameArg(a));a=this._ALL_NOTES.indexOf(a);++a==this._ALL_NOTES.length&&(a=0);return this._ALL_NOTES[a]};
Note.prototype.higher=function(a){return 0==arguments.length?this._higher():new Note(this.higherName(a))};Note.prototype.lowerName=function(a){a=this.validateNoteName(this._noteNameArg(a));a=this._ALL_NOTES.indexOf(a);0>--a&&(a=this._ALL_NOTES.length-1);return this._ALL_NOTES[a]};Note.prototype.lower=function(a){return 0==arguments.length?this._lower():new Note(this.lowerName(a))};
Note.prototype.higherSTName=function(a,b){var c=this.validateNoteName(this._noteNameArg(b));a=this._validateSemiTonesArg(a);if(0>a)return this.lowerSTName(-a,b);for(var d=0;d<a;d++)c=this.higherName(c);return c};Note.prototype.higherST=function(a,b){return 1==arguments.length?this._higherST(a):new Note(this.higherSTName(a,b))};
Note.prototype.lowerSTName=function(a,b){var c=this.validateNoteName(this._noteNameArg(b));a=this._validateSemiTonesArg(a);if(0>a)return this.higherSTName(-a,b);for(var d=0;d<a;d++)c=this.lowerName(c);return c};Note.prototype.lowerST=function(a,b){return 1==arguments.length?this._lowerST(a):new Note(this.lowerSTName(a,b))};Note.prototype.serialize=function(){return this._isValidSharp(this._noteName)?this.sharpToFlat():this._noteName};Note.prototype.deserialize=Note.prototype.set;
Note.prototype.toJSON=Note.prototype.serialize;Note.prototype.toString=Note.prototype.getName;function Scale(a,b){this._root=new Note;this._name=this.getDefaultName();this._semiTones=this.getDefaultSemiTones();this._isArgReceived(a)&&this.setName(a);this._isArgReceived(b)&&this.setRoot(b)}Scale.prototype._IS_DEBUG=IS_DEBUG;Scale.prototype._ALL_SCALES=SCALES;Scale.prototype._ST_SUM=12;Scale.prototype._isArgReceived=function(a){return void 0!==a};Scale.prototype._getSemiTonesFromName=function(a){return this._ALL_SCALES[a]};
Scale.prototype._isValidSemiTonesSum=function(a){for(var b=0,c=0;c<a.length;c++)b+=a[c];return b==this._ST_SUM?!0:!1};Scale.prototype.getDefaultName=function(){return"major"};Scale.prototype.getDefaultSemiTones=function(){return[2,2,1,2,2,2,1]};
Scale.prototype.isValidScaleName=function(a){if("string"!==typeof a)return this._IS_DEBUG&&console.error("Scale name must be a string"),!1;var b=this._getSemiTonesFromName(a);if(void 0!==b){if(this.isValidSemiTones(b))return!0;this._IS_DEBUG&&console.error("Invalid semitones for scale: "+a);return!1}this._IS_DEBUG&&console.error("Invalid scale Name: "+a);return!1};
Scale.prototype.isValidSemiTones=function(a){if("object"!==typeof a||!Array.isArray(a))return this._IS_DEBUG&&console.error("Semitones must be Array"),!1;if(this._isValidSemiTonesSum(a))return!0;this._IS_DEBUG&&console.error("Invalid semitones sum, must be: "+this._ST_SUM);return!1};Scale.prototype.setName=function(a){this.isValidScaleName(a)&&(this._name=a,this._semiTones=this._getSemiTonesFromName(a));return this};Scale.prototype.setRoot=function(a){this._root=new Note(a);return this};
Scale.prototype.getName=function(){return this._name};Scale.prototype.getRoot=function(){return this._root};Scale.prototype.getSemiTones=function(){return this._semiTones.slice()};Scale.prototype.getNotes=function(){var a=[],b=this._root.getCopy();a.push(b);for(var c=0;c<this._semiTones.length;c++)b=b.higherST(this._semiTones[c],b.getName()),a.push(b);a.pop();return a};Scale.prototype.getNotesNames=function(){return this.getNotes().map(function(a){return a.getName()})};
Scale.prototype.getSemiTonesPatternForString=function(a){a=a.getCopy();for(var b=this.getSemiTones(),c=this.getNotesNames(),d=[],e=0,f=c.indexOf(a.getName());0>f;)a.higher(),f=c.indexOf(a.getName()),e++;d.push(e);for(a=f;a<b.length;a++)d.push(b[a]);for(a=0;a<f;a++)d.push(b[a]);return d};Scale.prototype.serialize=function(){return[this._root,this._name]};Scale.prototype.deserialize=function(a){a&&(this.setRoot(a[0]),this.setName(a[1]));return this};Scale.prototype.toJSON=Scale.prototype.serialize;function GuitarTuning(a){this._name=this.getDefaultName();this._stringsTuning=this.getDefaultTunings();this._HS=0;this._isArgReceived(a)&&this.setName(a)}GuitarTuning.prototype._IS_DEBUG=IS_DEBUG;GuitarTuning.prototype._TUNINGS=TUNINGS;GuitarTuning.prototype._CUSTOM_NAME="custom";GuitarTuning.prototype._MIN_HS=-12;GuitarTuning.prototype._MAX_HS=12;GuitarTuning.prototype._isArgReceived=function(a){return void 0!==a};GuitarTuning.prototype._isValidTuningName=function(a){return this._TUNINGS.hasOwnProperty(a)};
GuitarTuning.prototype._isValidStringsTuning=function(a){return a.every(function(a,c,d){return a instanceof Note})};GuitarTuning.prototype._isValidHS=function(a){return Number.isInteger(a)&&a>=this._MIN_HS&&a<=this._MAX_HS};GuitarTuning.prototype.isValidStringsTuning=function(a){if(this._isValidStringsTuning(a))return!0;this._IS_DEBUG&&console.error("Invalid strings tuning: "+a);return!1};
GuitarTuning.prototype.isValidTuningName=function(a){if(this._isValidTuningName(a))return!0;this._IS_DEBUG&&console.error("Invalid strings tuning name: "+a);return!1};GuitarTuning.prototype.isInTunings=function(a){return this.getNameFromTunings(a)!==GuitarTuning._CUSTOM_NAME};GuitarTuning.prototype.isValidHS=function(a){if(this._isValidHS(a))return!0;this._IS_DEBUG&&console.error("Invalid strings tuning half-steps number: "+a);return!1};GuitarTuning.prototype.getDefaultName=function(){return"standart_e"};
GuitarTuning.prototype.getDefaultTunings=function(){return"E B G D A E B F# C# G# D# A#".split(" ").map(function(a){return new Note(a)})};GuitarTuning.prototype.getStringTuning=function(a){return this._stringsTuning[a%this._stringsTuning.length].getCopy().higherST(this._HS)};
GuitarTuning.prototype.setStringTuning=function(a,b){b.higherST(-this._HS);if(a>=this._stringsTuning.length){for(var c=this._stringsTuning.length;c<a;c++)this._stringsTuning.push(this.getStringTuning(c));this._stringsTuning.push(b)}else this._stringsTuning[a]=b;this.isInTunings(this._stringsTuning)?this._name=this.getNameFromTunings(this._stringsTuning):this._name=this._CUSTOM_NAME;return this};
GuitarTuning.prototype.setName=function(a){this.isValidTuningName(a)&&(this._name=a,this._stringsTuning=this._TUNINGS[a].map(function(a){return new Note(a)}));return this};GuitarTuning.prototype.getName=function(){return this._name};GuitarTuning.prototype.setTuning=function(a){this.isValidStringsTuning(a)&&(this._name=this.getNameFromTunings(a),this._stringsTuning=a);return this};GuitarTuning.prototype.setHS=function(a){this.isValidHS(a)&&(this._HS=a);return this};GuitarTuning.prototype.getHS=function(){return this._HS};
GuitarTuning.prototype.set=function(a,b,c){a===this._CUSTOM_NAME?(this._name=this._CUSTOM_NAME,this.setTuning(c)):this.setName(a);this._isArgReceived(b)&&this.setHS(b);return this};GuitarTuning.prototype.setFromArr=function(a){if(a)switch(a.length){case 1:this.set(a[0]);break;case 2:this.set(a[0],a[1]);break;case 3:this.set(a[0],a[1],a[2].map(function(a){return new Note(a)}));break;default:this._IS_DEBUG&&console.error("Ivalid argument length: "+a)}return this};
GuitarTuning.prototype.getNameFromTunings=function(a){if(!this.isValidStringsTuning(a))return this._CUSTOM_NAME;for(var b in this._TUNINGS)if(this._TUNINGS[b].length==a.length&&this._TUNINGS[b].every(function(b,d,e){return b==a[d].getName()}))return b;return this._CUSTOM_NAME};GuitarTuning.prototype.incHS=function(){var a=this._HS;this.isValidHS(++a)&&(this._HS=a);return this};GuitarTuning.prototype.decHS=function(){var a=this._HS;this.isValidHS(--a)&&(this._HS=a);return this};
GuitarTuning.prototype.serialize=function(){var a=[this._name,this._HS];this._name===this._CUSTOM_NAME&&a.push(this._stringsTuning);return a};GuitarTuning.prototype.deserialize=GuitarTuning.prototype.setFromArr;GuitarTuning.prototype.toJSON=GuitarTuning.prototype.serialize;function NotesShowPattern(){this._arr=Array(this._SIZE);for(var a=0;a<this._arr.length;a++)this._arr[a]=!0}NotesShowPattern.prototype._IS_DEBUG=IS_DEBUG;NotesShowPattern.prototype._SIZE=12;NotesShowPattern.prototype.set=function(a,b){a=Math.abs(a)%this._SIZE;isNaN(a)||(this._arr[a]=!!b);return this};NotesShowPattern.prototype.get=function(a){a=Math.abs(a)%this._SIZE;return this._arr[a]};NotesShowPattern.prototype.getArr=function(){return this._arr.slice()};
NotesShowPattern.prototype.toInt=function(){var a=this._arr.map(function(a){return+a});return parseInt(a.join(""),2)};NotesShowPattern.prototype.fromInt=function(a){a=Math.abs(a);if(isNaN(a))return this._IS_DEBUG&&console.error("Invalid number"),this;a=a.toString(2).split("");if(a.length<this._SIZE)for(var b=this._SIZE-a.length,c=0;c<b;c++)a.unshift("0");else a=a.slice(a.length-this._SIZE);this._arr=a.map(function(a){return!!+a});return this};NotesShowPattern.prototype.serialize=NotesShowPattern.prototype.toInt;
NotesShowPattern.prototype.deserialize=function(a){void 0!==a&&this.fromInt(a);return this};NotesShowPattern.prototype.toJSON=NotesShowPattern.prototype.serialize;var ParsingUt={isCorrectStringsNumber:function(a){return Number.isInteger(a)&&+a>=MIN_STRINGS_NUMBER&&+a<=MAX_STRINGS_NUMBER},validateStringsNumber:function(a){return ParsingUt.isCorrectStringsNumber(a)?a:6},isCorrectBoxFret:function(a){return Number.isInteger(a)&&-1<=a&&a<=FRETS_NUMBER},validateBoxFret:function(a){return ParsingUt.isCorrectBoxFret(a)?a:-1}};function sliderLogVal(a,b,c){var d=0;0<a&&(b=Math.log(b),d=Math.exp(b+(Math.log(c)-b)/100*(a-0)));return d};var defaults={init:function(){this.scales.init()}};defaults.scales={state:{},readFromCookie:function(){return Cookies.get("defaultScaleOptions")},saveToCookie:function(){Cookies.set("defaultScaleOptions",this.state,{expires:DEFAULT_SCALE_OPTIONS_EXPIRE_DAYS})},init:function(){this.state=new ScalesStateBase;this.state.deserialize(this.readFromCookie())}};var audioCtx,worker,isMetronomeCanWork=!1;try{audioCtx=new AudioContext,worker=new Worker("js/worker.js"),isMetronomeCanWork=!0}catch(a){console.error(a)}
var metronome={isPlaying:!1,beats:DEFAULT_METR_BEATS,beatValue:DEFAULT_METR_BEAT_VAL,volume:sliderLogVal(DEFAULT_METR_VOLUME,1,100)/100,tempo:DEFAULT_METR_TEMPO,nextBeatNumber:0,beatsQueue:[],$playBtn:$("#"+METR_PLAY_BTN_ID),$stopBtn:$("#"+METR_STOP_BTN_ID),$volumeRange:$("#"+METR_VOLUME_RANGE_ID),$tempoRange:$("#"+METR_TEMPO_RANGE_ID),$tempoOptionsBlock:$("#"+METR_TEMPO_OPTIONS_ID),$tempoInput:$("#"+METR_TEMPO_INPUT_ID),$tempoLeftArrow:$("#"+METR_TEMPO_LEFT_ARROW_ID),$tempoRightArrow:$("#"+METR_TEMPO_RIGHT_ARROW_ID),
$beatsSelect:$("#"+METR_BEATS_SELECT_ID),$beatsLeftArrow:$("#"+METR_BEATS_LEFT_ARROW_ID),$beatsRightArrow:$("#"+METR_BEATS_RIGHT_ARROW_ID),$beatValSelect:$("#"+METR_BEAT_VAL_SELECT_ID),$beatValLeftArrow:$("#"+METR_BEAT_VAL_LEFT_ARROW_ID),$beatValRightArrow:$("#"+METR_BEAT_VAL_RIGHT_ARROW_ID),$beatVisBlock:$("#"+METR_BEAT_VIS_BLOCK_ID),$beatVisNumber:$("#"+METR_BEAT_VIS_NUMBER_ID),$beatVisPointer:$("#"+METR_BEAT_VIS_POINTER_ID),scheduleBeatAudio:function(a){var b=audioCtx.createOscillator();b.type=
"square";var c=SECOND_CLICK_FREQ;0==a.number&&(c=FIRST_CLICK_FREQ);b.frequency.value=c;b.connect(this.gainNode);b.start(a.audioTime);b.stop(a.audioTime+50/c)},scheduleBeatVisual:function(a){var b=1E3*(a.audioTime-audioCtx.currentTime),c=1==a.number||1==this.beats;this.$beatVisPointer.toggleClass(METR_BEAT_VIS_POINTER_OTHER_CLASS,!c).toggleClass(METR_BEAT_VIS_POINTER_FIRST_CLASS,c);this.$beatVisPointer.rotate({duration:b,angle:0,animateTo:360,easing:function(a,b,c,g,l){return b/l*g+c}});setTimeout(function(){metronome.isPlaying&&
(metronome.$beatVisNumber.toggleClass(METR_FIRST_BEAT_VIS_NUMBER_CLASS,0==a.number),metronome.$beatVisNumber.text(a.number+1))},b)},scheduleBeatFromQueue:function(){if(0<this.beatsQueue.length){var a=this.beatsQueue.shift();this.scheduleBeatAudio(a);this.scheduleBeatVisual(a)}},beatsScheduler:function(){that=metronome;if(0<that.beatsQueue.length){var a=that.beatsQueue[that.beatsQueue.length-1],b=240/that.beatValue/that.tempo;audioCtx.currentTime+b>=a.audioTime&&(that.nextBeatNumber=(that.nextBeatNumber+
1)%that.beats,that.beatsQueue.push({audioTime:a.audioTime+b,number:that.nextBeatNumber}),that.scheduleBeatFromQueue())}else that.beatsQueue.push({audioTime:audioCtx.currentTime,number:0})},initTempoOptionsDatalist:function(){for(var a=MIN_TEMPO;a<=MAX_TEMPO;a+=TEMPO_OPTIONS_STEP)$(METR_DATALIST_OPTION_TMPL({tempo:a})).appendTo(this.$tempoOptionsBlock)},onPlayBtn:function(a){that=a.data.that;that.isPlaying=!0;$(this).hide();that.$stopBtn.show();that.$beatVisPointer.show();that.beatsQueue=[];that.nextBeatNumber=
0;worker.postMessage("startMetronomeTicking")},onStopBtn:function(a){that=a.data.that;that.isPlaying=!1;$(this).hide();that.$playBtn.show();that.$beatVisPointer.hide();that.$beatVisNumber.text("");worker.postMessage("stopMetronomeTicking")},onVolumeChange:function(a){that=a.data.that;a=$(this).val();a=sliderLogVal(+a,1,100);a/=100;that.gainNode.gain.value=a;that.volume=a},onTempoChange:function(a){that=a.data.that;a=$(this).val();that.$tempoInput.val(a);that.tempo=+a},onTempoInputChange:function(a){that=
a.data.that;a=$(this).val().replace(/[^,.0-9]/gim,"").replace(/[,.]+/gim,".");a=parseFloat(a);a<MIN_TEMPO?a=MIN_TEMPO:a>MAX_TEMPO&&(a=MAX_TEMPO);that.tempo=a;$(this).val(a);that.$tempoRange.val(a)},onTempoLeftArrow:function(a){that=a.data.that;a=that.$tempoInput.val();a>MIN_TEMPO&&(a--,that.tempo=a,that.$tempoInput.val(a),that.$tempoRange.val(a))},onTempoRightArrow:function(a){that=a.data.that;a=that.$tempoInput.val();a<MAX_TEMPO&&(a++,that.tempo=a,that.$tempoInput.val(a),that.$tempoRange.val(a))},
onBeatsChange:function(a){that=a.data.that;a=$(this).val();that.beats=+a},onBeatsLeftArrow:function(a){that=a.data.that;a=that.beats;a<=MIN_BEATS||(a--,that.beats=a,that.$beatsSelect.find("[value='"+a+"']").prop("selected",!0))},onBeatsRightArrow:function(a){that=a.data.that;a=that.beats;a>=MAX_BEATS||(a++,that.beats=a,that.$beatsSelect.find("[value='"+a+"']").prop("selected",!0))},onBeatValChange:function(a){that=a.data.that;a=$(this).val();that.beatValue=+a},onBeatValLeftArrow:function(a){that=
a.data.that;a=that.beatValue;a<=MIN_BEAT_VAL||(a/=2,that.beatValue=a,that.$beatValSelect.find("[value='"+a+"']").prop("selected",!0))},onBeatValRightArrow:function(a){that=a.data.that;a=that.beatValue;a>=MAX_BEAT_VAL||(a*=2,that.beatValue=a,that.$beatValSelect.find("[value='"+a+"']").prop("selected",!0))},workerTick:function(a){var b=metronome;"metronomeTick"==a.data&&b.beatsScheduler()},init:function(){this.$stopBtn.hide();this.$beatVisPointer.hide();isMetronomeCanWork&&($("#"+METRONOME_DISABLED_ID).hide(0),
this.initTempoOptionsDatalist(),this.tempo=+this.$tempoRange.val(),this.volume=sliderLogVal(+this.$volumeRange.val(),1,100)/100,this.gainNode=audioCtx.createGain(),this.gainNode.gain.value=this.volume,this.gainNode.connect(audioCtx.destination),worker.onmessage=this.workerTick,this.$tempoInput.val(this.tempo),this.beats=this.$beatsSelect.val(),this.beatValue=this.$beatValSelect.val(),this.$playBtn.click({that:this},this.onPlayBtn),this.$stopBtn.click({that:this},this.onStopBtn),this.$volumeRange.change({that:this},
this.onVolumeChange),this.$volumeRange.on("input",{that:this},this.onVolumeChange),this.$tempoRange.change({that:this},this.onTempoChange),this.$tempoRange.on("input",{that:this},this.onTempoChange),this.$tempoInput.change({that:this},this.onTempoInputChange),this.$tempoLeftArrow.click({that:this},this.onTempoLeftArrow),this.$tempoRightArrow.click({that:this},this.onTempoRightArrow),this.$beatsSelect.change({that:this},this.onBeatsChange),this.$beatsLeftArrow.click({that:this},this.onBeatsLeftArrow),
this.$beatsRightArrow.click({that:this},this.onBeatsRightArrow),this.$beatValSelect.change({that:this},this.onBeatValChange),this.$beatValLeftArrow.click({that:this},this.onBeatValLeftArrow),this.$beatValRightArrow.click({that:this},this.onBeatValRightArrow))}};function ColorSchemeSwitcher(){function a(){COLOR_SCHEMES_CLASSES.forEach(function(a){b.toggleClass(a,!1)})}var b=$("."+BG_BLOCK_CLASS),c={day:$("#"+COMMON_SETTINGS_BLOCK_DAY_COLOR_BTN_ID),night:$("#"+COMMON_SETTINGS_BLOCK_NIGHT_COLOR_BTN_ID)},d="night";this.saveToCookies=function(){Cookies.set("colorScheme",d)};this.switchScheme=function(c){0<=COLOR_SCHEMES_CLASSES.indexOf(c)&&(d=c,a(),b.toggleClass(d,!0),this.saveToCookies())};this.onSwitchToDayColorBtn=function(a){a=a.data.that;$(this).hide();
c.night.show();a.switchScheme("day")};this.onSwitchToNightColorBtn=function(a){a=a.data.that;$(this).hide();c.day.show();a.switchScheme("night")};this.initButtons=function(){"day"==d?c.day.hide():c.night.hide();c.day.click({that:this},this.onSwitchToDayColorBtn);c.night.click({that:this},this.onSwitchToNightColorBtn)};this.init=function(){void 0!==Cookies.getJSON("colorScheme")&&(d=Cookies.getJSON("colorScheme"));this.switchScheme(d);this.initButtons()}}
var commonSettings={$openBtn:$("#"+COMMON_SETTINGS_BTN_ID),$closeBtn:$("#"+COMMON_SETTINGS_BLOCK_CLOSE_BTN_ID),$settingsBlock:$("#"+COMMON_SETTINGS_BLOCK_ID),colorSchemeSwitcher:new ColorSchemeSwitcher,isShown:!1,showMenuToggle:function(a){a?this.$settingsBlock.slideDown(100):this.$settingsBlock.slideUp(100)},onOpenBtnClick:function(a){a=a.data.that;a.isShown=!a.isShown;a.showMenuToggle(a.isShown)},onCloseBtnClick:function(a){a=a.data.that;a.isShown=!1;a.showMenuToggle(a.isShown)},init:function(){this.$settingsBlock.toggleClass(COMMON_SETTINGS_BLOCK_HIDE_CLASS,
!1);this.$settingsBlock.hide();this.$openBtn.click({that:this},this.onOpenBtnClick);this.$closeBtn.click({that:this},this.onCloseBtnClick);this.$settingsBlock.parent().on("clickoutside",{that:this},this.onCloseBtnClick);this.colorSchemeSwitcher.init()}};function ItemBase(a,b){this.init(a,b)}ItemBase.prototype.deleteItem=function(){var a=$(this);menuItems.deleteItem(a.attr("id"));a.remove()};ItemBase.prototype.onItemTypeChange=function(a){$(this).val().toLowerCase()};ItemBase.prototype.onCloseButton=function(a){a=a.data.that;a.$itemBlock.slideUp(200,a.deleteItem)};ItemBase.prototype.onSetDefaultButton=function(a){a.data.that.item.state.saveToDefaultOptions()};ItemBase.prototype.initAnimation=function(){this.$itemBlock.hide();this.$itemBlock.slideDown(200)};
ItemBase.prototype.init=function(a,b){menuItems.$addNewItemBtn.before(ITEM_BASE_BLOCK_TMPL({id:a}));this.$itemBlock=$("#"+a);this.item=itemsFactory.getItem(a,b);this.initAnimation();$("."+ITEM_HEAD_SELECT_CLASS,this.$itemBlock).change({that:this},this.onItemTypeChange);$("."+CLOSE_BTN_CLASS,this.$itemBlock).click({that:this},this.onCloseButton);$("."+SET_DEFAULT_BTN_CLASS,this.$itemBlock).click({that:this},this.onSetDefaultButton)};function StringsTuning(a,b,c){this.state=a;this.$stringsTuningBlock=b;this.tuneBlocks=[];this.tuneChangeEventAction=c;this.init()}
StringsTuning.prototype.addStringTuning=function(a){var b=$(STRING_TUNE_BLOCK_TMPL()).appendTo(this.$stringsTuningBlock);$("."+STRING_TUNE_SELECT_CLASS+" :contains('"+a.getName()+"')",b).prop("selected",!0);$("."+STRING_TUNE_SELECT_CLASS,b).change({that:this},this.onStringTuneChange);$("."+LEFT_ARROW_CLASS,b).click({that:this},this.onLeftArrowTuneClick);$("."+RIGHT_ARROW_CLASS,b).click({that:this},this.onRightArrowTuneClick);this.tuneBlocks.push(b)};StringsTuning.prototype.delLastString=function(){this.tuneBlocks.pop().remove()};
StringsTuning.prototype.selectCurrentStringsTunes=function(){for(var a=0;a<this.state.stringsNumber;a++){var b=this.state.tuning.getStringTuning(a);this.$stringsTuningBlock.find("."+STRING_TUNE_SELECT_CLASS+":eq("+a+") :contains('"+b.getName()+"')").prop("selected",!0)}};
StringsTuning.prototype.onStringTuneChange=function(a){a=a.data.that;var b=$(this).val(),c=$("."+STRING_TUNE_SELECT_CLASS,a.$stringsTuningBlock).index(this);a.state.tuning.setStringTuning(c,new Note(b));a.tuneChangeEventAction(c);a.state.saveToQuery()};
StringsTuning.prototype.onLeftArrowTuneClick=function(a){a=a.data.that;var b=$("."+LEFT_ARROW_CLASS,a.$stringsTuningBlock).index(this),c=a.state.tuning.getStringTuning(b);a.state.tuning.setStringTuning(b,c.lower());$("."+STRING_TUNE_SELECT_CLASS+":eq("+b+") :contains('"+c.getName()+"')",a.$stringsTuningBlock).prop("selected",!0);a.tuneChangeEventAction(b);a.state.saveToQuery()};
StringsTuning.prototype.onRightArrowTuneClick=function(a){a=a.data.that;var b=$("."+RIGHT_ARROW_CLASS,a.$stringsTuningBlock).index(this),c=a.state.tuning.getStringTuning(b);a.state.tuning.setStringTuning(b,c.higher());$("."+STRING_TUNE_SELECT_CLASS+":eq("+b+") :contains('"+c.getName()+"')",a.$stringsTuningBlock).prop("selected",!0);a.tuneChangeEventAction(b);a.state.saveToQuery()};
StringsTuning.prototype.init=function(){for(var a=0;a<this.state.stringsNumber;a++)this.addStringTuning(this.state.tuning.getStringTuning(a));this.selectCurrentStringsTunes()};function Fretboard(a,b){this.state=a;this.$fretboardBlock=b;this.notesBlocks=[];this.verFrets=[];this.init()}
Fretboard.prototype.putNote=function(a,b,c,d){c=$(this.notesBlocks[c][b]);c.toggleClass(HIDDEN_NOTE_CLASS,!1);var e=this.state.scale.getNotesNames().indexOf(a);d=-1==this.state.boxFirstFret||b>=this.state.boxFirstFret&&b<this.state.boxFirstFret+d;this.state.isTriadMode?(b=!this.state.triadsNotesShowPattern.get(e),c.text(e+1)):(b=!this.state.normalNotesShowPattern.get(e),c.text(a));!b&&d||c.toggleClass(TRANSPARENT_NOTE_CLASS,!0);a=a==this.state.scale.getRoot().getName();c.toggleClass(NORMAL_NOTE_CLASS,
!a).toggleClass(HIGHLIGHTED_NOTE_CLASS,a)};Fretboard.prototype.putNotesOnString=function(a){var b=this.calculateNotesBoxSize(a,this.state.boxFirstFret),c=this.state.tuning.getStringTuning(a),d=this.state.scale.getSemiTonesPatternForString(c),e=$(this.notesBlocks[a]);e.toggleClass(HIDDEN_NOTE_CLASS,!0);e.toggleClass(TRANSPARENT_NOTE_CLASS,!1);for(var f=d.shift(),c=c.higherST(f),g=0;f<e.length;)this.putNote(c.getName(),f,a,b),f+=d[g],c.higherST(d[g]),g=++g%d.length};
Fretboard.prototype.putNotesOnAllStrings=function(){for(var a=0;a<this.state.stringsNumber;a++)this.putNotesOnString(a)};Fretboard.prototype.putNotesOnNearStrings=function(a){var b=a-1;a+=1;0<=b&&this.putNotesOnString(b);a<this.state.stringsNumber&&this.putNotesOnString(a)};
Fretboard.prototype.calculateNotesBoxSize=function(a,b){var c=0;if(0<a){var d=this.state.tuning.getStringTuning(a-1),e=this.state.tuning.getStringTuning(a);d.higherST(b);e.higherST(b);if(e.getName()==d.getName())return 1;for(;e.getName()!=d.getName();)e.higher(),e!=d&&c++}else c=4;return c};Fretboard.prototype.calculateNotesBoxSizeForAllStrings=function(a){for(var b=0,c=this.state.stringsNumber-1;0<=c;c--){var d=this.calculateNotesBoxSize(c,a);d>b&&(b=d)}return b};
Fretboard.prototype.isBoxFit=function(a,b){return a+b<=FRETS_NUMBER};
Fretboard.prototype.addString=function(a){for(var b={currentStringNumber:Math.min(a+1,MAX_STRINGS_STYLE)},c=this.verFrets,d,e,f=0;f<c.length;f++)d=$(STRING_FRET_TMPL(b)).appendTo(c[f]),d=$("."+NOTE_CLASS,d)[0],void 0===this.notesBlocks[a]&&(this.notesBlocks[a]=[]),this.notesBlocks[a][f]=d,0==a&&(d=1==f||3==f||5==f||7==f||9==f||15==f||17==f||19==f||21==f,e=12==f||24==f,d?($(c[f]).append(STRING_FRET_MARK_TMPL()),$(FRET_DOT_TMPL()).insertAfter(c[f])):e&&($(c[f]).append(STRING_DOUBLE_FRET_MARK_TMPL()),
$(FRET_DOUBLE_DOT_TMPL()).insertAfter(c[f])));this.putNotesOnString(a)};Fretboard.prototype.delLastString=function(){for(var a=0;a<this.verFrets.length;a++)$("."+HOR_FRET_CLASS,$(this.verFrets[a])).last().remove()};
Fretboard.prototype.onFretClick=function(a){a=a.data.that;var b=a.$fretboardBlock.find("."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS).index(this);if(a.state.boxFirstFret==b)a.state.boxFirstFret=-1;else{var c=a.calculateNotesBoxSizeForAllStrings(b);a.isBoxFit(b,c)&&(a.state.boxFirstFret=b)}a.putNotesOnAllStrings();a.state.saveToQuery()};
Fretboard.prototype.onFretHoverIn=function(a){var b=a.data.that;a=b.$fretboardBlock.find("."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS).index(this);var c=b.calculateNotesBoxSizeForAllStrings(a);if(b.isBoxFit(a,c))for(var b=$("."+FRET_HOVER_CLASS,b.$fretboardBlock),d=0;d<c;d++){var e=FRET_HOVER_ACTIVE_CENTER_CLASS;0==d?e=FRET_HOVER_ACTIVE_START_CLASS:d==c-1&&(e=FRET_HOVER_ACTIVE_END_CLASS);$(b[a+d]).toggleClass(e,!0)}};
Fretboard.prototype.onFretHoverOut=function(a){a.data.that.$fretboardBlock.find("."+FRET_HOVER_CLASS).toggleClass(FRET_HOVER_ACTIVE_START_CLASS,!1).toggleClass(FRET_HOVER_ACTIVE_CENTER_CLASS,!1).toggleClass(FRET_HOVER_ACTIVE_END_CLASS,!1)};
Fretboard.prototype.init=function(){for(var a=0;a<FRETS_NUMBER;a++)this.$fretboardBlock.children().last().before(STRING_VER_FRET_TMPL());this.verFrets=$("."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS,this.$fretboardBlock);for(a=0;a<this.state.stringsNumber;a++)this.addString(a);this.$fretboardBlock.on("click","."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS,{that:this},this.onFretClick);this.$fretboardBlock.on("mouseenter","."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS,{that:this},this.onFretHoverIn);
this.$fretboardBlock.on("mouseleave","."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS,{that:this},this.onFretHoverOut)};function Neck(a,b,c,d,e,f,g){this.state=a;this.$neckBlock=b;this.$stringsNumberBlock=c;this.$addStringBtn=d;this.$delStringBtn=e;this.$tuningOptionsBlock=f;this.$lhToggleBlock=g;var l=this;this.fretboard=new Fretboard(a,$("."+FRETBOARD_CLASS,b));this.stringsTunings=new StringsTuning(a,$("."+STRINGS_OPTIONS_BLOCK_CLASS,b),function(a){l.putNotesOnString(a);l.fretboard.putNotesOnNearStrings(a);l.selectCurrentTuning()});this.init()}Neck.prototype.putNotesOnString=function(a){this.fretboard.putNotesOnString(a)};
Neck.prototype.putNotesOnAllStrings=function(){this.fretboard.putNotesOnAllStrings()};Neck.prototype.selectCurrentStringsTunes=function(){this.stringsTunings.selectCurrentStringsTunes()};Neck.prototype.selectCurrentTuning=function(){this.$tuningOptionsBlock.find("."+TUNING_SELECT_CLASS+" [value='"+this.state.tuning.getName()+"']").prop("selected",!0)};
Neck.prototype.switchLH=function(){this.$lhToggleBlock.find("."+TOGGLE_SLIDER_CLASS).toggleClass(SLIDER_LH_CLASS,this.state.isLH).toggleClass(SLIDER_RH_CLASS,!this.state.isLH);this.$neckBlock.toggleClass(LH_CLASS,this.state.isLH)};Neck.prototype.switchLHevent=function(){this.state.isLH=!this.state.isLH;this.switchLH();this.state.saveToQuery()};
Neck.prototype.onTuningChange=function(a){a=a.data.that;var b=$(this).val().toLowerCase();a.state.tuning.setName(b);a.putNotesOnAllStrings();a.selectCurrentStringsTunes();a.state.saveToQuery()};Neck.prototype.selectCurrentHalfStep=function(){$("."+HALF_STEP_SELECT_CLASS+" [value='"+this.state.tuning.getHS()+"']",this.$tuningOptionsBlock).prop("selected",!0)};
Neck.prototype.onHalfStepChange=function(a){a=a.data.that;newValue=+$(this).val();a.state.tuning.setHS(newValue);a.selectCurrentStringsTunes();a.putNotesOnAllStrings();a.state.saveToQuery()};Neck.prototype.onLeftArrowHalfStepClick=function(a){a=a.data.that;a.state.tuning.decHS();a.selectCurrentStringsTunes();a.putNotesOnAllStrings();a.selectCurrentHalfStep();a.state.saveToQuery()};
Neck.prototype.onRightArrowHalfStepCLick=function(a){a=a.data.that;a.state.tuning.incHS();a.selectCurrentStringsTunes();a.putNotesOnAllStrings();a.selectCurrentHalfStep();a.state.saveToQuery()};
Neck.prototype.onAddStringButton=function(a){a=a.data.that;if(a.state.stringsNumber<MAX_STRINGS_NUMBER){a.fretboard.addString(a.state.stringsNumber);var b=a.state.tuning.getStringTuning(a.state.stringsNumber);a.stringsTunings.addStringTuning(b);a.state.stringsNumber++;a.$stringsNumberBlock.text(""+a.state.stringsNumber);a.state.saveToQuery()}};
Neck.prototype.onDelStringButton=function(a){a=a.data.that;a.state.stringsNumber>MIN_STRINGS_NUMBER&&(a.fretboard.delLastString(),a.stringsTunings.delLastString(),a.state.stringsNumber--,a.$stringsNumberBlock.text(""+a.state.stringsNumber),a.state.saveToQuery())};Neck.prototype.onLhToggleSlider=function(a){a.data.that.switchLHevent()};Neck.prototype.onLhToggleClick=function(a){a=a.data.that;a.state.isLH||a.switchLHevent()};Neck.prototype.onRhToggleClick=function(a){a=a.data.that;a.state.isLH&&a.switchLHevent()};
Neck.prototype.init=function(){this.$stringsNumberBlock.text(""+this.state.stringsNumber);this.selectCurrentTuning();this.selectCurrentHalfStep();this.putNotesOnAllStrings();this.switchLH();this.$addStringBtn.click({that:this},this.onAddStringButton);this.$delStringBtn.click({that:this},this.onDelStringButton);$("."+TUNING_SELECT_CLASS,this.$tuningOptionsBlock).change({that:this},this.onTuningChange);$("."+HALF_STEP_SELECT_CLASS,this.$tuningOptionsBlock).change({that:this},this.onHalfStepChange);
this.$tuningOptionsBlock.find("."+HALF_STEP_BLOCK_CLASS).find("."+LEFT_ARROW_CLASS).click({that:this},this.onLeftArrowHalfStepClick);this.$tuningOptionsBlock.find("."+HALF_STEP_BLOCK_CLASS).find("."+RIGHT_ARROW_CLASS).click({that:this},this.onRightArrowHalfStepCLick);this.$lhToggleBlock.find("."+TOGGLE_CHECKBOX_CLASS).click({that:this},this.onLhToggleSlider);this.$lhToggleBlock.find("."+LH_TOGGLE_CLASS).click({that:this},this.onLhToggleClick);this.$lhToggleBlock.find("."+RH_TOGGLE_CLASS).click({that:this},
this.onRhToggleClick)};function ScalesStateBase(){this.type=SCALES_TYPE;this.scale=new Scale;this.tuning=new GuitarTuning;this.stringsNumber=6;this.isTriadMode=!1;this.normalNotesShowPattern=new NotesShowPattern;this.triadsNotesShowPattern=(new NotesShowPattern).deserialize(2688);this.boxFirstFret=-1;this.isLH=!1}ScalesStateBase.prototype.toArr=function(){return[this.type,this.scale,this.tuning,+this.stringsNumber,+this.isTriadMode,this.normalNotesShowPattern,this.triadsNotesShowPattern,this.boxFirstFret,+this.isLH]};
ScalesStateBase.prototype.serialize=function(){return JSON.stringify(this.toArr())};ScalesStateBase.prototype.toJSON=ScalesStateBase.prototype.toArr;
ScalesStateBase.prototype.deserialize=function(a){var b=[];if(a)try{b=JSON.parse(a)}catch(c){console.error("Invalid JSON: "+a)}this.scale=(new Scale).deserialize(b[1]);this.tuning=(new GuitarTuning).deserialize(b[2]);this.stringsNumber=ParsingUt.validateStringsNumber(b[3]);this.isTriadMode=!!b[4];this.normalNotesShowPattern.deserialize(b[5]);this.triadsNotesShowPattern.deserialize(b[6]);this.boxFirstFret=ParsingUt.validateBoxFret(b[7]);this.isLH=!!b[8]};
function ScalesItemState(a,b){ScalesStateBase.call(this);this.id=a;this.init(b)}ScalesItemState.prototype=Object.create(ScalesStateBase.prototype);ScalesItemState.prototype.saveToQuery=function(){menuItems.updateItemSerializedData(this.id,this.serialize());menuItems.updateItemsQueryParams()};ScalesItemState.prototype.saveToDefaultOptions=function(){defaults.scales.state.deserialize(this.serialize());defaults.scales.saveToCookie()};ScalesItemState.prototype.readFromDefaultOptions=function(){this.deserialize(defaults.scales.state.serialize())};
ScalesItemState.prototype.init=function(a){this.readFromDefaultOptions();a&&this.deserialize(a);this.saveToQuery()};function ScalesItem(a,b){this.state=new ScalesItemState(a,b);this.$itemBlock=$("#"+a);this.init()}ScalesItem.prototype.putNotesOnAllStrings=function(){this.neck.putNotesOnAllStrings()};ScalesItem.prototype.selectCurrentStringsTunes=function(){this.neck.selectCurrentStringsTunes()};ScalesItem.prototype.selectCurrentScale=function(){$("."+SCALE_SELECT_CLASS+" [value='"+this.state.scale.getName()+"']",this.$itemBlock).prop("selected",!0)};
ScalesItem.prototype.updateScaleNotesBlock=function(){$("."+SCALE_NOTES_CLASS,this.$itemBlock).remove();var a=this.state.scale.getNotes(),b=this.state.scale.getRoot();a.push(b);a=a.map(function(a){return a.getName()});a={root:a[0],semiTones:this.state.scale.getSemiTones(),notes:a};$("."+SCALE_NOTES_BLOCK_CLASS,this.$itemBlock).append(SCALE_NOTES_TMPL(a));var a=$("."+SCALE_NOTES_CLASS,this.$itemBlock).find("."+SCALE_NOTE_TEXT_CLASS),b=a.length-1,c=this.state.normalNotesShowPattern.getArr();this.state.isTriadMode&&
(c=this.state.triadsNotesShowPattern.getArr());for(var d=0;d<b;d++)if(!c[d]){var e=$(a[d]);e.toggleClass(TRANSPARENT_BLOCK_CLASS,!0);0==d&&(e=$(a[b]),e.toggleClass(TRANSPARENT_BLOCK_CLASS,!0))}$("."+SCALE_NOTES_CLASS,this.$itemBlock).on("click","."+SCALE_NOTE_CLASS,{that:this},this.onScaleNoteClick)};
ScalesItem.prototype.selectCurrentRootNote=function(){$("."+ROOT_NOTE_CLASS+"."+SELECTED_TEXT_CLASS,this.$itemBlock).toggleClass(SELECTED_TEXT_CLASS,!1);$("."+ROOT_NOTE_CLASS+":contains('"+this.state.scale.getRoot().getName()+"')",this.$itemBlock).first().toggleClass(SELECTED_TEXT_CLASS,!0)};ScalesItem.prototype.onScaleChange=function(a){a=a.data.that;var b=$(this).val().toLowerCase();a.state.scale.setName(b);a.putNotesOnAllStrings();a.updateScaleNotesBlock();a.state.saveToQuery()};
ScalesItem.prototype.onRootNoteChange=function(a){a=a.data.that;var b=$(this).text();a.state.scale.setRoot(b);a.selectCurrentRootNote();a.updateScaleNotesBlock();a.putNotesOnAllStrings();a.state.saveToQuery()};
ScalesItem.prototype.onScaleNoteClick=function(a){a=a.data.that;var b=$("."+SCALE_NOTE_CLASS,a.$itemBlock).index(this),b=b%a.state.scale.getNotes().length,c;a.state.isTriadMode?(c=!a.state.triadsNotesShowPattern.get(b),a.state.triadsNotesShowPattern.set(b,c)):(c=!a.state.normalNotesShowPattern.get(b),a.state.normalNotesShowPattern.set(b,c));0==b?(b=$("."+SCALE_NOTE_CLASS,a.$itemBlock).last().find("."+SCALE_NOTE_TEXT_CLASS),b.toggleClass(TRANSPARENT_BLOCK_CLASS,!c),b=$("."+SCALE_NOTE_CLASS,a.$itemBlock).first().find("."+
SCALE_NOTE_TEXT_CLASS)):b=$(this).find("."+SCALE_NOTE_TEXT_CLASS);b.toggleClass(TRANSPARENT_BLOCK_CLASS,!c);a.putNotesOnAllStrings();a.state.saveToQuery()};ScalesItem.prototype.onTriadsCheckboxClick=function(a){a=a.data.that;a.state.isTriadMode?(a.state.isTriadMode=!1,a.$triadsCheckbox.hide(),a.$triadsCheckboxEmpty.show()):(a.state.isTriadMode=!0,a.$triadsCheckboxEmpty.hide(),a.$triadsCheckbox.show());a.updateScaleNotesBlock();a.putNotesOnAllStrings();a.state.saveToQuery()};
ScalesItem.prototype.initTriadsCheckbox=function(){this.$triadsCheckbox=$("."+TRIADS_CHECKBOX_CLASS,this.$itemBlock);this.$triadsCheckboxEmpty=$("."+TRIADS_CHECKBOX_EMPTY_CLASS,this.$itemBlock);this.state.isTriadMode?this.$triadsCheckboxEmpty.hide():this.$triadsCheckbox.hide();this.$triadsCheckbox.click({that:this},this.onTriadsCheckboxClick);this.$triadsCheckboxEmpty.click({that:this},this.onTriadsCheckboxClick)};
ScalesItem.prototype.initDOM=function(){this.$itemOptionsBlock=$("."+ITEM_OPTIONS_BLOCK,this.$itemBlock);this.$stringsBtnsBlock=$(STRINGS_BTNS_BLOCK_TMPL()).insertBefore($("."+ITEM_HEAD_SELECT_CLASS,this.$itemBlock));this.$lhToggleBlock=$(LH_TOGGLE_BLOCK_TMPL()).insertAfter($("."+ITEM_HEAD_SELECT_CLASS,this.$itemBlock));this.$neckBlock=$(NECK_BLOCK_TMPL()).insertAfter($("."+ITEM_HEAD_CLASS,this.$itemBlock));this.$scalesOptionsBlock=$(SCALES_OPTIONS_BLOCK_TMPL()).prependTo(this.$itemOptionsBlock);
this.$scalesSelectBlock=$(SCALES_SELECT_BLOCK_TMPL()).prependTo(this.$itemOptionsBlock);this.$TuningOptionsBlock=$(TUNING_OPTIONS_BLOCK_TMPL()).prependTo(this.$itemOptionsBlock)};
ScalesItem.prototype.init=function(){this.initDOM();this.neck=new Neck(this.state,this.$neckBlock,$("."+STRING_NUMBER_CLASS,this.$itemBlock),$("."+ADD_STRING_BTN_CLASS,this.$itemBlock),$("."+DEL_STRING_BTN_CLASS,this.$itemBlock),$("."+TUNING_OPTIONS_CLASS,this.$itemBlock),this.$lhToggleBlock);this.initTriadsCheckbox();this.updateScaleNotesBlock();this.selectCurrentScale();this.selectCurrentRootNote();$("."+SCALE_SELECT_CLASS,this.$itemBlock).change({that:this},this.onScaleChange);$("."+SCALE_NOTES_BLOCK_CLASS,
this.$itemBlock).on("click","."+ROOT_NOTE_CLASS,{that:this},this.onRootNoteChange)};itemsFactory={getItem:function(a,b){var c;c=[];var d="";if(b)try{c=JSON.parse(b),d=c[0]}catch(e){console.error("Invalid JSON: "+b)}switch(d){case SCALES_TYPE:c=new ScalesItem(a,b);break;case CHORDS_TYPE:c=new ChordsItem(a,b);break;default:console.error("Invalid item type: "+d),c=new ScalesItem(a)}return c}};var menuItems={itemsNumber:0,items:{},itemsSerializedStates:{},getIDforNewItem:function(){for(var a=0;void 0!==this.items[ITEMS_ID_BASE+a];)a++;return ITEMS_ID_BASE+a},deleteItem:function(a){this.itemsNumber==MAX_ITEMS_NUMBER&&this.$addNewItemBtn.show(200);delete this.items[a]&&(delete this.itemsSerializedStates[a],this.updateItemsQueryParams(),this.itemsNumber--)},updateItemsQueryParams:function(){for(var a="?",b=0;b<MAX_ITEMS_NUMBER;b++){var c=ITEMS_ID_BASE+b;void 0!==this.itemsSerializedStates[c]&&
(0!=b&&(a+="&"),a+="i"+b+"="+this.encodeQueryParamString(this.itemsSerializedStates[c]))}history.replaceState({},"",a)},updateItemSerializedData:function(a,b){this.itemsSerializedStates[a]=b},createNewItem:function(){var a=this.getIDforNewItem();this.itemsNumber<MAX_ITEMS_NUMBER?(this.items[a]=new ItemBase(a),this.itemsNumber++):this.$addNewItemBtn.hide(200)},createItemsFromQueryParams:function(a){for(var b=0;b<a.length&&b<MAX_ITEMS_NUMBER;b++){var c=this.getIDforNewItem();this.items[c]=new ItemBase(c,
a[b]);this.itemsNumber++}this.itemsNumber>=MAX_ITEMS_NUMBER&&this.$addNewItemBtn.hide(200)},readItemsQueryParams:function(){var a=window.location.href,b=a.indexOf("?"),c=[];if(-1!=b)for(var a=a.slice(b+1).split("&"),d=0;d<a.length&&d<MAX_ITEMS_NUMBER;d++)b=a[d].indexOf("="),-1!=b&&(b=a[d].slice(b+1),b=this.decodeQueryParamString(b),c.push(b));return c},encodeQueryParamString:function(a){var b="",c=a[a.length-1];"["==a[0]&&"]"==c&&(b=a.replace(/["']/g,""));return b},decodeQueryParamString:function(a){var b=
"",c=a[a.length-1];"["==a[0]&&"]"==c&&(b=a.replace(/[^\d,\[\]"'-]\w*#*/g,function(a){return'"'+a+'"'}));return b},onNewItemButton:function(a){that=a.data.that;that.createNewItem()},init:function(){this.$addNewItemBtn=$("#"+ADD_NEW_ITEM_BTN_ID);this.$addNewItemBtn.click({that:this},this.onNewItemButton);var a=this.readItemsQueryParams();0==a.length?this.createNewItem():this.createItemsFromQueryParams(a)}};metronome.init();commonSettings.init();defaults.init();menuItems.init();
