var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6-impl","es3");
$jscomp.polyfill("Number.isInteger",function(a){return a?a:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6-impl","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6-impl","es3");
(function(a){if("function"===typeof define&&define.amd)define(a);else if("object"===typeof exports)module.exports=a();else{var b=window.Cookies,c=window.Cookies=a();c.noConflict=function(){window.Cookies=b;return c}}})(function(){function a(){for(var a=0,b={};a<arguments.length;a++){var e=arguments[a],f;for(f in e)b[f]=e[f]}return b}function b(c){function d(b,f,g){var e;if("undefined"!==typeof document){if(1<arguments.length){g=a({path:"/"},d.defaults,g);if("number"===typeof g.expires){var k=new Date;
k.setMilliseconds(k.getMilliseconds()+864E5*g.expires);g.expires=k}try{e=JSON.stringify(f),/^[\{\[]/.test(e)&&(f=e)}catch(p){}f=c.write?c.write(f,b):encodeURIComponent(String(f)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent);b=encodeURIComponent(String(b));b=b.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);b=b.replace(/[\(\)]/g,escape);return document.cookie=[b,"=",f,g.expires&&"; expires="+g.expires.toUTCString(),g.path&&"; path="+g.path,g.domain&&
"; domain="+g.domain,g.secure?"; secure":""].join("")}b||(e={});for(var k=document.cookie?document.cookie.split("; "):[],q=/(%[0-9A-Z]{2})+/g,n=0;n<k.length;n++){var r=k[n].split("="),h=r.slice(1).join("=");'"'===h.charAt(0)&&(h=h.slice(1,-1));try{var m=r[0].replace(q,decodeURIComponent),h=c.read?c.read(h,m):c(h,m)||h.replace(q,decodeURIComponent);if(this.json)try{h=JSON.parse(h)}catch(p){}if(b===m){e=h;break}b||(e[m]=h)}catch(p){}}return e}}d.set=d;d.get=function(a){return d(a)};d.getJSON=function(){return d.apply({json:!0},
[].slice.call(arguments))};d.defaults={};d.remove=function(b,c){d(b,"",a(c,{expires:-1}))};d.withConverter=b;return d}return b(function(){})});var SCALE_SEMITONES_NUMBER=12,MAX_HALF_STEP=11,MIN_HALF_STEP=-11,MAX_STRINGS_NUMBER=12,MIN_STRINGS_NUMBER=3,MAX_ITEMS_NUMBER=5,ITEMS_ID_BASE="menuItem",FRETS_NUMBER=24,DEFAULT_METR_BEATS=4,DEFAULT_METR_BEAT_VAL=4,DEFAULT_METR_VOLUME=50,DEFAULT_METR_TEMPO=120,MIN_BEATS=1,MAX_BEATS=16,MIN_BEAT_VAL=1,MAX_BEAT_VAL=32,MIN_TEMPO=40,MAX_TEMPO=320,TEMPO_OPTIONS_STEP=5,SECOND_CLICK_FREQ=880,FIRST_CLICK_FREQ=1480,DEFAULT_SCALE_OPTIONS_EXPIRE_DAYS=30,DEFAULT_NOTES_SHOW_PATTERN=[!0,!0,!0,!0,!0,!0,!0,!0,!0,!0,
!0,!0],DEFAULT_TRIADS_SHOW_PATTERN=[!0,!1,!0,!1,!0,!1,!1,!1,!1,!1,!1,!1],NOTES="C C# D D# E F F# G G# A A# B".split(" "),DEFAULT_SCALE_SEMITONES=[2,2,1,2,2,2,1],DEFAULT_STRING_TUNES="E B G D A E B F# C# G# D# A#".split(" "),DEFAULT_SCALE_NOTES="CDEFGAB".split(""),SCALES={major:[2,2,1,2,2,2,1],aeolian:[2,2,1,2,2,2,1],minor:[2,1,2,2,1,2,2],ionian:[2,1,2,2,1,2,2],harmonic_min:[2,1,2,2,1,3,1],chromatic:[1,1,1,1,1,1,1,1,1,1,1,1],dorian:[2,1,2,2,2,1,2],phrygian:[1,2,2,2,1,2,2],lydian:[2,2,2,1,2,2,1],myxolydian:[2,
2,1,2,2,1,2],locrian:[1,2,2,1,2,2,2],melodic_min:[2,1,2,2,2,2,1],alt_dom:[1,2,1,2,2,2,2],sup_locrian:[1,2,1,2,2,2,2],dim_whole_tone:[1,2,1,2,2,2,2],alt_scale:[1,2,1,2,2,2,2],blues_min_hex:[3,2,1,1,3,2],blues_pent:[3,2,1,4,2],blues:[3,2,1,1,3,1,1],major_pent:[2,2,3,2,3],suspended_pent:[2,3,2,3,2],dorian_pent:[2,3,2,3,2],phrygian_pent:[3,2,3,2,2],myxolydian_pent:[2,3,2,2,3],aeolian_pent:[3,2,2,3,2],minor_pent:[3,2,2,3,2],major_beb:[2,2,1,2,1,1,2,1],minor_beb:[2,1,1,1,2,2,1,2],dom_beb:[2,2,1,2,2,1,1,
1],dorian_beb:[2,1,1,1,2,2,1,2],whole_tone:[2,2,2,2,2,2],whole_half_tone:[2,1,2,1,2,1,2,1],half_whole_tone:[1,2,1,2,1,2,1,2],dim:[2,1,2,1,2,1,2,1],dom_dim:[1,2,1,2,1,2,1,2],symm_dim:[1,2,1,2,1,2,1,2],spanish:[1,2,2,2,1,2,2],acoustic:[2,2,2,1,2,1,2],bartok:[2,2,2,1,2,1,2]},CHORDS={min_triad:["1","b3","5"],min_6:["1","b3","5","6"],min_b6:["1","b3","5","b6"],min_7:["1","b3","5","b7"],min_9:["1","b3","5","b7","b9"],min_11:"1 b3 5 b7 (9) 11".split(" "),min_13:"1 b3 5 b7 (9) (11) 13".split(" "),min_maj_7:["1",
"b3","5","7"],min_7_f5:["1","b3","b5","b7"],full_dim:["1","b3","b5","bb7"],maj_triad:["1","3","5"],maj_6:["1","3","5","6"],maj_7:["1","3","5","7"],maj_9:["1","3","5","7","9"],maj_11:"1 3 5 7 (9) 11".split(" "),maj_13:"1 3 5 7 (9) (11) 13".split(" "),sus_2:["1","2","5"],sus_4:["1","4","5"],dom_7:["1","3","5","b7"],dom_9:["1","3","5","b7","b9"],dom_11:"1 3 5 b7 (9) 11".split(" "),dom_13:"1 3 5 b7 (9) (11) 13".split(" "),dim_triad:["1","b3","b5"],aug_triad:["1","3","#5"]},TUNINGS={standart_e:"E B G D A E B F# C# G# D# A#".split(" "),
standart_e_bass:["G","D","A","E","B"],standart_e_bass_6:"CGDAEB".split(""),drop_d_6:"E B G D A D B F# C# G# D# A#".split(" "),drop_a_7:"E B G D A E A F# C# G# D# A#".split(" "),drop_e_8:"E B G D A E B E C# G# D# A#".split(" ")},CUSTOM_TUNING_VALUE="custom",COLOR_SCHEMES_CLASSES=["day","night"],SCALES_TYPE="scales",CHORDS_TYPE="chords",BG_BLOCK_CLASS="bg_block",ITEM_CLASS="item_block",ITEM_CONTENT_CLASS="item_content",ITEM_HEAD_CLASS="item_head",ITEM_HEAD_SELECT_CLASS="item_head_select",ITEM_OPTIONS_BLOCK=
"item_options_block",STRING_NUMBER_CLASS="strings_number",SCALE_SELECT_CLASS="scale_select",NECK_BLOCK_CLASS="neck_block",FRETBOARD_CLASS="fretboard",HOR_FRET_CLASS="fret_hor",NULL_VER_FRET_CLASS="fret_null",VER_FRET_CLASS="fret_ver",VER_FRET_INNER_CLASS="fret_ver_inner",FRET_HOVER_CLASS="fret_ver_hover",FRET_HOVER_ACTIVE_CENTER_CLASS="fret_ver_hover_active_center",FRET_HOVER_ACTIVE_START_CLASS="fret_ver_hover_active_start",FRET_HOVER_ACTIVE_END_CLASS="fret_ver_hover_active_end",NOTE_CLASS="note",
NORMAL_NOTE_CLASS="normal_note",HIGHLIGHTED_NOTE_CLASS="highlighted_note",TRANSPARENT_NOTE_CLASS="transparent_note",HIDDEN_NOTE_CLASS="hidden_note",STRINGS_OPTIONS_BLOCK_CLASS="strings_options_block",STRING_TUNE_BLOCK_CLASS="string_tune",STRING_TUNE_SELECT_CLASS="string_tune_select",LEFT_ARROW_CLASS="left_arrow",RIGHT_ARROW_CLASS="right_arrow",TUNING_OPTIONS_CLASS="tuning_options",HALF_STEP_BLOCK_CLASS="half_step_block",HALF_STEP_SELECT_CLASS="half_step_select",TUNING_SELECT_CLASS="tuning_select",
ROOT_NOTE_CLASS="root_note",SELECTED_TEXT_CLASS="selected_text",SCALE_NOTES_BLOCK_CLASS="scale_notes_and_semitones_block",SCALE_NOTES_CLASS="scale_notes",SCALE_NOTE_CLASS="scale_note",SCALE_NOTE_TEXT_CLASS="scale_note_text",ADD_STRING_BTN_CLASS="add_string",DEL_STRING_BTN_CLASS="delete_string",CLOSE_BTN_CLASS="close_btn",SET_DEFAULT_BTN_CLASS="set_default_btn",TRIADS_CHECKBOX_CLASS="triads_checkbox",TRIADS_CHECKBOX_EMPTY_CLASS="triads_checkbox_empty",LH_TOGGLE_BLOCK_CLASS="lh_toggle_block",TOGGLE_CHECKBOX_CLASS=
"toggle_checkbox",LH_TOGGLE_CLASS="lh_toggle",RH_TOGGLE_CLASS="rh_toggle",TOGGLE_SLIDER_CLASS="toggle_checkbox_slider",SLIDER_LH_CLASS="slider_lh",SLIDER_RH_CLASS="slider_rh",LH_CLASS="lh",TRANSPARENT_BLOCK_CLASS="transparent_block",METRONOME_DISABLED_ID="metronome_disabled_block",ADD_NEW_ITEM_BTN_ID="add_new_item_btn",METR_PLAY_BTN_ID="metronome_play_btn",METR_STOP_BTN_ID="metronome_stop_btn",METR_VOLUME_RANGE_ID="metronome_volume_range",METR_TEMPO_RANGE_ID="metronome_tempo_range",METR_TEMPO_OPTIONS_ID=
"tempos",METR_TEMPO_INPUT_ID="metronome_tempo_input",METR_TEMPO_LEFT_ARROW_ID="metronome_tempo_left_arrow",METR_TEMPO_RIGHT_ARROW_ID="metronome_tempo_right_arrow",METR_BEATS_SELECT_ID="metronome_beats_select",METR_BEATS_LEFT_ARROW_ID="metronome_beats_left_arrow",METR_BEATS_RIGHT_ARROW_ID="metronome_beats_right_arrow",METR_BEAT_VAL_SELECT_ID="metronome_beat_val_select",METR_BEAT_VAL_LEFT_ARROW_ID="metronome_beat_val_left_arrow",METR_BEAT_VAL_RIGHT_ARROW_ID="metronome_beat_val_right_arrow",METR_BEAT_VIS_BLOCK_ID=
"metronome_beat_vis_block",METR_BEAT_VIS_NUMBER_ID="metronome_beat_number_vis",METR_BEAT_VIS_POINTER_ID="metronome_pointer_block",METR_BEAT_VIS_POINTER_FIRST_CLASS="metronome_pointer_first",METR_BEAT_VIS_POINTER_OTHER_CLASS="metronome_pointer_other",METR_FIRST_BEAT_VIS_NUMBER_CLASS="metronome_first_beat_number_vis",COMMON_SETTINGS_BTN_ID="common_settings_btn",COMMON_SETTINGS_BLOCK_ID="settings_block",COMMON_SETTINGS_BLOCK_HIDE_CLASS="settings_block_hide",COMMON_SETTINGS_BLOCK_CLOSE_BTN_ID="settings_close_btn",
COMMON_SETTINGS_BLOCK_NIGHT_COLOR_BTN_ID="color_scheme_switch_night_btn",COMMON_SETTINGS_BLOCK_DAY_COLOR_BTN_ID="color_scheme_switch_day_btn",WRONG_ITEM_TYPE_MSG="Wrong item type",WRONG_SEMITONE_NUMBER_MSG="Wrong sum of semitones, must be equal to "+SCALE_SEMITONES_NUMBER,WRONG_ROOT_NOTE_MSG="Wrong root note",WRONG_NOTE_MSG="Wrong note",WRONG_SCALE_NAME_MSG="Wrong scale name (value)",WRONG_STRING_TUNE_NOTE_MSG="Wrong string tune note",WRONG_TUNING_NAME="Wrong tuning name (value)",PARAMS_ATOB_ERROR_MSG=
"GET parameter cannot be decoded",METR_DATALIST_OPTION_TMPL=doT.template($("#metronome_datalist_option_tmpl").html()),ITEM_BASE_BLOCK_TMPL=doT.template($("#item_base_tmpl").html()),STRINGS_BTNS_BLOCK_TMPL=doT.template($("#strings_btns_tmpl").html()),LH_TOGGLE_BLOCK_TMPL=doT.template($("#lh_toggle_tmpl").html()),NECK_BLOCK_TMPL=doT.template($("#neck_tmpl").html()),TUNING_OPTIONS_BLOCK_TMPL=doT.template($("#tuning_options_tmpl").html()),SCALES_SELECT_BLOCK_TMPL=doT.template($("#scales_select_tmpl").html()),
SCALES_OPTIONS_BLOCK_TMPL=doT.template($("#scales_options_tmpl").html()),SCALE_NOTES_TMPL=doT.template($("#scale_notes_tmpl").html()),STRING_VER_FRET_TMPL=doT.template($("#string_ver_fret_tmpl").html()),STRING_FRET_TMPL=doT.template($("#string_hor_fret_tmpl").html()),STRING_FRET_MARK_TMPL=doT.template($("#fretboard_single_mark").html()),STRING_DOUBLE_FRET_MARK_TMPL=doT.template($("#fretboard_double_mark").html()),FRET_DOT_TMPL=doT.template($("#fret_dot_tmpl").html()),FRET_DOUBLE_DOT_TMPL=doT.template($("#fret_double_dot_tmpl").html()),
STRING_TUNE_BLOCK_TMPL=doT.template($("#string_tune_block_tmpl").html());var Note={isCorrect:function(a){if("string"!==typeof a)return!1;var b=!1;0<=NOTES.indexOf(a.toUpperCase())?b=!0:console.log(a+": "+WRONG_NOTE_MSG);return b},next:function(a){resultNote="C";Note.isCorrect(a)&&(a=NOTES.indexOf(a),a++,a==NOTES.length&&(a=0),resultNote=NOTES[a]);return resultNote},prev:function(a){resultNote="C";Note.isCorrect(a)&&(a=NOTES.indexOf(a),a--,0>a&&(a=NOTES.length-1),resultNote=NOTES[a]);return resultNote},nextSemiTones:function(a,b){var c=a;if(0<b)for(var d=0;d<b;d++)c=Note.next(c);
else for(d=0;d>b;d--)c=Note.prev(c);return c},getNotesFromSemiTones:function(a,b){var c=DEFAULT_SCALE_NOTES;a=a.toUpperCase();if(Note.isCorrect(a)&&Scale.isCorrectSemitonesSum(b)){var c=[],d=a;c.push(d);for(var e=0;e<b.length;e++){for(var f=1;f<=b[e];f++)d=Note.next(d);c.push(d)}c.pop()}return c}};var Tuning={isCorrect:function(a){if("string"!==typeof a)return!1;var b=!1;if(a==CUSTOM_TUNING_VALUE)b=!0;else{var c=TUNINGS[a];void 0!==c?b=Tuning.isCorrectNotes(c):console.log(a+": "+WRONG_TUNING_NAME)}return b},isCorrectNotes:function(a){if("object"!==typeof a||!Array.isArray(a))return!1;for(var b=!1,c=0;c<a.length&&(b=Note.isCorrect(a[c]),b);c++);return b},getStringsTunes:function(a){a=a.toLowerCase();var b=DEFAULT_STRING_TUNES;Tuning.isCorrect(a)&&(b=TUNINGS[a].slice());return b},getStringTune:function(a,
b){return a[b%a.length]},getTuningName:function(a){var b=CUSTOM_TUNING_VALUE,c;for(c in TUNINGS)if(TUNINGS[c].length==a.length&&TUNINGS[c].every(function(b,c,f){return b==a[c]}))return c;return b}};var Scale={isCorrect:function(a){if("string"!==typeof a)return!1;var b=!1,c=SCALES[a];void 0!==c?b=Scale.isCorrectSemitonesSum(c):console.log(a+": "+WRONG_SCALE_NAME_MSG);return b},isCorrectSemitonesSum:function(a){if("object"!==typeof a||!Array.isArray(a))return!1;for(var b=!1,c=0,d=0;d<a.length;d++)c+=a[d];c==SCALE_SEMITONES_NUMBER?b=!0:console.log(a+": "+WRONG_SEMITONE_NUMBER_MSG);return b},getSemitones:function(a){a=a.toLowerCase();var b=DEFAULT_SCALE_SEMITONES;Scale.isCorrect(a)&&(b=SCALES[a]);
return b}};var Halfstep={isCorrect:function(a){return Number.isInteger(a)&&+a>=MIN_HALF_STEP&&+a<=MAX_HALF_STEP},prev:function(a){a--;a<MIN_HALF_STEP&&(a=MIN_HALF_STEP);return a},next:function(a){a++;a>MAX_HALF_STEP&&(a=MAX_HALF_STEP);return a}};var ParsingUt={isCorrectStringsNumber:function(a){return Number.isInteger(a)&&+a>=MIN_STRINGS_NUMBER&&+a<=MAX_STRINGS_NUMBER},isCorrectNotesShowPattern:function(a){var b="object"===typeof a&&Array.isArray(a);if(!b)return!1;var c=a.every(function(a){return"boolean"===typeof a});if(!c)return!1;a=12==a.length;return b&&c&&a},isCorrectBoxFret:function(a){return Number.isInteger(a)&&-1<=a&&a<=FRETS_NUMBER},semiTonesPatternBoolToInt:function(a,b){if(ParsingUt.isCorrectStringsNumber(b))for(var c=0;c<b.length;c++)b[c]=
b[c]?1:0;return b},semiTonesPatternIntToBool:function(a,b){var c="object"===typeof b&&Array.isArray(b);if(!c)return b;var d=b.every(function(a){return Number.isInteger(a)});if(!d)return b;var e=12==b.length;if(c&&d&&e)for(c=0;c<b.length;c++)b[c]=0!==b[c];return b}};function getSemiTonesPatternForString(a,b,c){for(var d=[],e=0,f=a.indexOf(c);0>f;)c=Note.next(c),f=a.indexOf(c),e++;d.push(e);for(a=f;a<b.length;a++)d.push(b[a]);for(a=0;a<f;a++)d.push(b[a]);return d}function sliderLogVal(a,b,c){var d=0;0<a&&(b=Math.log(b),d=Math.exp(b+(Math.log(c)-b)/100*(a-0)));return d};var defaults={init:function(){this.scales.init()}};defaults.scales={scale:"major",root:"C",tuning:"standart_e",halfStep:0,stringsTunes:DEFAULT_STRING_TUNES,stringsNumber:6,isTriadMode:!1,normalNotesShowPattern:DEFAULT_NOTES_SHOW_PATTERN,triadsNotesShowPattern:DEFAULT_TRIADS_SHOW_PATTERN,boxFirstFret:-1,isLH:!1,readFromCookie:function(){if(void 0!==Cookies.getJSON("defaultScaleOptions")){var a=Cookies.getJSON("defaultScaleOptions");void 0!==a.scale&&Scale.isCorrect(a.scale)&&(this.scale=a.scale);void 0!==a.root&&Note.isCorrect(a.root)&&(this.root=
a.root);void 0!==a.tuning&&Tuning.isCorrect(a.tuning)&&(this.tuning=a.tuning);void 0!==a.halfStep&&Halfstep.isCorrect(a.halfStep)&&(this.halfStep=+a.halfStep);void 0!==a.stringsTunes&&Tuning.isCorrectNotes(a.stringsTunes)&&(this.stringsTunes=a.stringsTunes);void 0!==a.stringsNumber&&ParsingUt.isCorrectStringsNumber(a.stringsNumber)&&(this.stringsNumber=+a.stringsNumber);void 0!==a.isTriadMode&&"boolean"===typeof a.isTriadMode&&(this.isTriadMode=a.isTriadMode);void 0!==a.normalNotesShowPattern&&ParsingUt.isCorrectNotesShowPattern(a.normalNotesShowPattern)&&
(this.normalNotesShowPattern=a.normalNotesShowPattern);void 0!==a.triadsNotesShowPattern&&ParsingUt.isCorrectNotesShowPattern(a.triadsNotesShowPattern)&&(this.triadsNotesShowPattern=a.triadsNotesShowPattern);void 0!==a.boxFirstFret&&ParsingUt.isCorrectBoxFret(a.boxFirstFret)&&(this.boxFirstFret=a.boxFirstFret);void 0!==a.isLH&&"boolean"===typeof a.isLH&&(this.isLH=a.isLH)}},saveToCookie:function(){Cookies.set("defaultScaleOptions",this,{expires:DEFAULT_SCALE_OPTIONS_EXPIRE_DAYS})},init:function(){this.readFromCookie()}};var audioCtx,worker,isMetronomeCanWork=!1;try{audioCtx=new AudioContext,worker=new Worker("js/worker.js"),isMetronomeCanWork=!0}catch(a){console.log(a)}
var metronome={isPlaying:!1,beats:DEFAULT_METR_BEATS,beatValue:DEFAULT_METR_BEAT_VAL,volume:sliderLogVal(DEFAULT_METR_VOLUME,1,100)/100,tempo:DEFAULT_METR_TEMPO,nextBeatNumber:0,beatsQueue:[],$playBtn:$("#"+METR_PLAY_BTN_ID),$stopBtn:$("#"+METR_STOP_BTN_ID),$volumeRange:$("#"+METR_VOLUME_RANGE_ID),$tempoRange:$("#"+METR_TEMPO_RANGE_ID),$tempoOptionsBlock:$("#"+METR_TEMPO_OPTIONS_ID),$tempoInput:$("#"+METR_TEMPO_INPUT_ID),$tempoLeftArrow:$("#"+METR_TEMPO_LEFT_ARROW_ID),$tempoRightArrow:$("#"+METR_TEMPO_RIGHT_ARROW_ID),
$beatsSelect:$("#"+METR_BEATS_SELECT_ID),$beatsLeftArrow:$("#"+METR_BEATS_LEFT_ARROW_ID),$beatsRightArrow:$("#"+METR_BEATS_RIGHT_ARROW_ID),$beatValSelect:$("#"+METR_BEAT_VAL_SELECT_ID),$beatValLeftArrow:$("#"+METR_BEAT_VAL_LEFT_ARROW_ID),$beatValRightArrow:$("#"+METR_BEAT_VAL_RIGHT_ARROW_ID),$beatVisBlock:$("#"+METR_BEAT_VIS_BLOCK_ID),$beatVisNumber:$("#"+METR_BEAT_VIS_NUMBER_ID),$beatVisPointer:$("#"+METR_BEAT_VIS_POINTER_ID),scheduleBeatAudio:function(a){var b=audioCtx.createOscillator();b.type=
"square";var c=SECOND_CLICK_FREQ;0==a.number&&(c=FIRST_CLICK_FREQ);b.frequency.value=c;b.connect(this.gainNode);b.start(a.audioTime);b.stop(a.audioTime+50/c)},scheduleBeatVisual:function(a){var b=1E3*(a.audioTime-audioCtx.currentTime),c=1==a.number||1==this.beats;this.$beatVisPointer.toggleClass(METR_BEAT_VIS_POINTER_OTHER_CLASS,!c).toggleClass(METR_BEAT_VIS_POINTER_FIRST_CLASS,c);this.$beatVisPointer.rotate({duration:b,angle:0,animateTo:360,easing:function(a,b,c,g,l){return b/l*g+c}});setTimeout(function(){metronome.isPlaying&&
(metronome.$beatVisNumber.toggleClass(METR_FIRST_BEAT_VIS_NUMBER_CLASS,0==a.number),metronome.$beatVisNumber.text(a.number+1))},b)},scheduleBeatFromQueue:function(){if(0<this.beatsQueue.length){var a=this.beatsQueue.shift();this.scheduleBeatAudio(a);this.scheduleBeatVisual(a)}},beatsScheduler:function(){that=metronome;if(0<that.beatsQueue.length){var a=that.beatsQueue[that.beatsQueue.length-1],b=240/that.beatValue/that.tempo;audioCtx.currentTime+b>=a.audioTime&&(that.nextBeatNumber=(that.nextBeatNumber+
1)%that.beats,that.beatsQueue.push({audioTime:a.audioTime+b,number:that.nextBeatNumber}),that.scheduleBeatFromQueue())}else that.beatsQueue.push({audioTime:audioCtx.currentTime,number:0})},initTempoOptionsDatalist:function(){for(var a=MIN_TEMPO;a<=MAX_TEMPO;a+=TEMPO_OPTIONS_STEP)$(METR_DATALIST_OPTION_TMPL({tempo:a})).appendTo(this.$tempoOptionsBlock)},onPlayBtn:function(a){that=a.data.that;that.isPlaying=!0;$(this).hide();that.$stopBtn.show();that.$beatVisPointer.show();that.beatsQueue=[];that.nextBeatNumber=
0;worker.postMessage("startMetronomeTicking")},onStopBtn:function(a){that=a.data.that;that.isPlaying=!1;$(this).hide();that.$playBtn.show();that.$beatVisPointer.hide();that.$beatVisNumber.text("");worker.postMessage("stopMetronomeTicking")},onVolumeChange:function(a){that=a.data.that;a=$(this).val();a=sliderLogVal(+a,1,100);a/=100;that.gainNode.gain.value=a;that.volume=a},onTempoChange:function(a){that=a.data.that;a=$(this).val();that.$tempoInput.val(a);that.tempo=+a},onTempoInputChange:function(a){that=
a.data.that;a=$(this).val().replace(/[^,.0-9]/gim,"").replace(/[,.]+/gim,".");a=parseFloat(a);a<MIN_TEMPO?a=MIN_TEMPO:a>MAX_TEMPO&&(a=MAX_TEMPO);that.tempo=a;$(this).val(a);that.$tempoRange.val(a)},onTempoLeftArrow:function(a){that=a.data.that;a=that.$tempoInput.val();a>MIN_TEMPO&&(a--,that.tempo=a,that.$tempoInput.val(a),that.$tempoRange.val(a))},onTempoRightArrow:function(a){that=a.data.that;a=that.$tempoInput.val();a<MAX_TEMPO&&(a++,that.tempo=a,that.$tempoInput.val(a),that.$tempoRange.val(a))},
onBeatsChange:function(a){that=a.data.that;a=$(this).val();that.beats=+a},onBeatsLeftArrow:function(a){that=a.data.that;a=that.beats;a<=MIN_BEATS||(a--,that.beats=a,that.$beatsSelect.find("[value='"+a+"']").prop("selected",!0))},onBeatsRightArrow:function(a){that=a.data.that;a=that.beats;a>=MAX_BEATS||(a++,that.beats=a,that.$beatsSelect.find("[value='"+a+"']").prop("selected",!0))},onBeatValChange:function(a){that=a.data.that;a=$(this).val();that.beatValue=+a},onBeatValLeftArrow:function(a){that=
a.data.that;a=that.beatValue;a<=MIN_BEAT_VAL||(a/=2,that.beatValue=a,that.$beatValSelect.find("[value='"+a+"']").prop("selected",!0))},onBeatValRightArrow:function(a){that=a.data.that;a=that.beatValue;a>=MAX_BEAT_VAL||(a*=2,that.beatValue=a,that.$beatValSelect.find("[value='"+a+"']").prop("selected",!0))},workerTick:function(a){var b=metronome;"metronomeTick"==a.data&&b.beatsScheduler()},init:function(){this.$stopBtn.hide();this.$beatVisPointer.hide();isMetronomeCanWork&&($("#"+METRONOME_DISABLED_ID).hide(0),
this.initTempoOptionsDatalist(),this.tempo=+this.$tempoRange.val(),this.volume=sliderLogVal(+this.$volumeRange.val(),1,100)/100,this.gainNode=audioCtx.createGain(),this.gainNode.gain.value=this.volume,this.gainNode.connect(audioCtx.destination),worker.onmessage=this.workerTick,this.$tempoInput.val(this.tempo),this.beats=this.$beatsSelect.val(),this.beatValue=this.$beatValSelect.val(),this.$playBtn.click({that:this},this.onPlayBtn),this.$stopBtn.click({that:this},this.onStopBtn),this.$volumeRange.change({that:this},
this.onVolumeChange),this.$volumeRange.on("input",{that:this},this.onVolumeChange),this.$tempoRange.change({that:this},this.onTempoChange),this.$tempoRange.on("input",{that:this},this.onTempoChange),this.$tempoInput.change({that:this},this.onTempoInputChange),this.$tempoLeftArrow.click({that:this},this.onTempoLeftArrow),this.$tempoRightArrow.click({that:this},this.onTempoRightArrow),this.$beatsSelect.change({that:this},this.onBeatsChange),this.$beatsLeftArrow.click({that:this},this.onBeatsLeftArrow),
this.$beatsRightArrow.click({that:this},this.onBeatsRightArrow),this.$beatValSelect.change({that:this},this.onBeatValChange),this.$beatValLeftArrow.click({that:this},this.onBeatValLeftArrow),this.$beatValRightArrow.click({that:this},this.onBeatValRightArrow))}};function ColorSchemeSwitcher(){function a(){COLOR_SCHEMES_CLASSES.forEach(function(a){b.toggleClass(a,!1)})}var b=$("."+BG_BLOCK_CLASS),c={day:$("#"+COMMON_SETTINGS_BLOCK_DAY_COLOR_BTN_ID),night:$("#"+COMMON_SETTINGS_BLOCK_NIGHT_COLOR_BTN_ID)},d="night";this.saveToCookies=function(){Cookies.set("colorScheme",d)};this.switchScheme=function(c){0<=COLOR_SCHEMES_CLASSES.indexOf(c)&&(d=c,a(),b.toggleClass(d,!0),this.saveToCookies())};this.onSwitchToDayColorBtn=function(a){a=a.data.that;$(this).hide();
c.night.show();a.switchScheme("day")};this.onSwitchToNightColorBtn=function(a){a=a.data.that;$(this).hide();c.day.show();a.switchScheme("night")};this.initButtons=function(){"day"==d?c.day.hide():c.night.hide();c.day.click({that:this},this.onSwitchToDayColorBtn);c.night.click({that:this},this.onSwitchToNightColorBtn)};this.init=function(){void 0!==Cookies.getJSON("colorScheme")&&(d=Cookies.getJSON("colorScheme"));this.switchScheme(d);this.initButtons()}}
var commonSettings={$openBtn:$("#"+COMMON_SETTINGS_BTN_ID),$closeBtn:$("#"+COMMON_SETTINGS_BLOCK_CLOSE_BTN_ID),$settingsBlock:$("#"+COMMON_SETTINGS_BLOCK_ID),colorSchemeSwitcher:new ColorSchemeSwitcher,isShown:!1,showMenuToggle:function(a){a?this.$settingsBlock.slideDown(100):this.$settingsBlock.slideUp(100)},onOpenBtnClick:function(a){a=a.data.that;a.isShown=!a.isShown;a.showMenuToggle(a.isShown)},onCloseBtnClick:function(a){a=a.data.that;a.isShown=!1;a.showMenuToggle(a.isShown)},init:function(){this.$settingsBlock.toggleClass(COMMON_SETTINGS_BLOCK_HIDE_CLASS,
!1);this.$settingsBlock.hide();this.$openBtn.click({that:this},this.onOpenBtnClick);this.$closeBtn.click({that:this},this.onCloseBtnClick);this.$settingsBlock.parent().on("clickoutside",{that:this},this.onCloseBtnClick);this.colorSchemeSwitcher.init()}};function ItemBase(a,b){this.init(a,b)}ItemBase.prototype.deleteItem=function(){var a=$(this);menuItems.deleteItem(a.attr("id"));a.remove()};ItemBase.prototype.onItemTypeChange=function(a){$(this).val().toLowerCase()};ItemBase.prototype.onCloseButton=function(a){a=a.data.that;a.$itemBlock.slideUp(200,a.deleteItem)};ItemBase.prototype.onSetDefaultButton=function(a){a.data.that.item.state.saveToDefaultOptions()};ItemBase.prototype.initAnimation=function(){this.$itemBlock.hide();this.$itemBlock.slideDown(200)};
ItemBase.prototype.init=function(a,b){menuItems.$addNewItemBtn.before(ITEM_BASE_BLOCK_TMPL({id:a}));this.$itemBlock=$("#"+a);this.item=itemsFactory.getItem(a,b);this.initAnimation();$("."+ITEM_HEAD_SELECT_CLASS,this.$itemBlock).change({that:this},this.onItemTypeChange);$("."+CLOSE_BTN_CLASS,this.$itemBlock).click({that:this},this.onCloseButton);$("."+SET_DEFAULT_BTN_CLASS,this.$itemBlock).click({that:this},this.onSetDefaultButton)};function StringsTuning(a,b,c){this.state=a;this.$stringsTuningBlock=b;this.tuneBlocks=[];this.tuneChangeEventAction=c;this.init()}
StringsTuning.prototype.addStringTuning=function(a){var b=$(STRING_TUNE_BLOCK_TMPL()).appendTo(this.$stringsTuningBlock);$("."+STRING_TUNE_SELECT_CLASS+" :contains('"+a+"')",b).prop("selected",!0);$("."+STRING_TUNE_SELECT_CLASS,b).change({that:this},this.onStringTuneChange);$("."+LEFT_ARROW_CLASS,b).click({that:this},this.onLeftArrowTuneClick);$("."+RIGHT_ARROW_CLASS,b).click({that:this},this.onRightArrowTuneClick);this.tuneBlocks.push(b)};StringsTuning.prototype.delLastString=function(){this.tuneBlocks.pop().remove()};
StringsTuning.prototype.selectCurrentStringsTunes=function(){for(var a=0;a<this.state.stringsNumber;a++){var b=Tuning.getStringTune(this.state.stringsTunes,a);this.$stringsTuningBlock.find("."+STRING_TUNE_SELECT_CLASS+":eq("+a+") :contains('"+b+"')").prop("selected",!0)}};
StringsTuning.prototype.onStringTuneChange=function(a){a=a.data.that;var b=$(this).val(),c=$("."+STRING_TUNE_SELECT_CLASS,a.$stringsTuningBlock).index(this);a.state.stringsTunes[c]=b;a.state.tuning=Tuning.getTuningName(a.state.stringsTunes);a.tuneChangeEventAction(c);a.state.saveToQuery()};
StringsTuning.prototype.onLeftArrowTuneClick=function(a){a=a.data.that;var b=$("."+LEFT_ARROW_CLASS,a.$stringsTuningBlock).index(this),c=a.state.stringsTunes[b],c=Note.prev(c);a.state.stringsTunes[b]=c;$("."+STRING_TUNE_SELECT_CLASS+":eq("+b+") :contains('"+c+"')",a.$stringsTuningBlock).prop("selected",!0);a.state.tuning=Tuning.getTuningName(a.state.stringsTunes);a.tuneChangeEventAction(b);a.state.saveToQuery()};
StringsTuning.prototype.onRightArrowTuneClick=function(a){a=a.data.that;var b=$("."+RIGHT_ARROW_CLASS,a.$stringsTuningBlock).index(this),c=a.state.stringsTunes[b],c=Note.next(c);a.state.stringsTunes[b]=c;$("."+STRING_TUNE_SELECT_CLASS+":eq("+b+") :contains('"+c+"')",a.$stringsTuningBlock).prop("selected",!0);a.state.tuning=Tuning.getTuningName(a.state.stringsTunes);a.tuneChangeEventAction(b);a.state.saveToQuery()};
StringsTuning.prototype.init=function(){for(var a=0;a<this.state.stringsNumber;a++)this.addStringTuning(Tuning.getStringTune(this.state.stringsTunes,a))};function Fretboard(a,b){this.state=a;this.$fretboardBlock=b;this.notesBlocks=[];this.verFrets=[];this.init()}
Fretboard.prototype.putNote=function(a,b,c,d){c=$(this.notesBlocks[c][b]);c.toggleClass(HIDDEN_NOTE_CLASS,!1);var e=this.state.scaleNotes.indexOf(a);d=-1==this.state.boxFirstFret||b>=this.state.boxFirstFret&&b<=this.state.boxFirstFret+d;this.state.isTriadMode?(b=!this.state.triadsNotesShowPattern[e],c.text(e+1)):(b=!this.state.normalNotesShowPattern[e],c.text(a));!b&&d||c.toggleClass(TRANSPARENT_NOTE_CLASS,!0);a=a==this.state.root;c.toggleClass(NORMAL_NOTE_CLASS,!a).toggleClass(HIGHLIGHTED_NOTE_CLASS,
a)};Fretboard.prototype.putNotesOnString=function(a){var b=this.calculateNotesBoxSize(a,this.state.boxFirstFret),c=Tuning.getStringTune(this.state.stringsTunes,a),d=getSemiTonesPatternForString(this.state.scaleNotes,this.state.semiTones,c),e=$(this.notesBlocks[a]);e.toggleClass(HIDDEN_NOTE_CLASS,!0);e.toggleClass(TRANSPARENT_NOTE_CLASS,!1);for(var f=d.shift(),c=Note.nextSemiTones(c,f),g=0;f<e.length;)this.putNote(c,f,a,b),f+=d[g],c=Note.nextSemiTones(c,d[g]),g=++g%d.length};
Fretboard.prototype.putNotesOnAllStrings=function(){for(var a=0;a<this.state.stringsNumber;a++)this.putNotesOnString(a)};Fretboard.prototype.putNotesOnNearStrings=function(a){0==a?this.putNotesOnString(1):a==this.state.stringsNumber?this.putNotesOnString(a-1):(this.putNotesOnString(a-1),this.putNotesOnString(a+1))};
Fretboard.prototype.calculateNotesBoxSize=function(a,b){var c=0;if(0<a)for(var d=Tuning.getStringTune(this.state.stringsTunes,a-1),e=Tuning.getStringTune(this.state.stringsTunes,a),d=Note.nextSemiTones(d,b),e=Note.nextSemiTones(e,b);e!=d;)e=Note.next(e),e!=d&&c++;else c=4;return c};Fretboard.prototype.calculateNotesBoxSizeForAllStrings=function(a){for(var b=0,c=0;c<this.state.stringsNumber;c++){var d=this.calculateNotesBoxSize(c,a);d>b&&(b=d)}return b};
Fretboard.prototype.isBoxFit=function(a,b){return a+b<=FRETS_NUMBER};
Fretboard.prototype.addString=function(a){for(var b={currentStringNumber:a+1},c=this.verFrets,d,e,f=0;f<c.length;f++)d=$(STRING_FRET_TMPL(b)).appendTo(c[f]),d=$("."+NOTE_CLASS,d)[0],void 0===this.notesBlocks[a]&&(this.notesBlocks[a]=[]),this.notesBlocks[a][f]=d,0==a&&(d=1==f||3==f||5==f||7==f||9==f||15==f||17==f||19==f||21==f,e=12==f||24==f,d?($(c[f]).append(STRING_FRET_MARK_TMPL()),$(FRET_DOT_TMPL()).insertAfter(c[f])):e&&($(c[f]).append(STRING_DOUBLE_FRET_MARK_TMPL()),$(FRET_DOUBLE_DOT_TMPL()).insertAfter(c[f])));
this.putNotesOnString(a)};Fretboard.prototype.delLastString=function(){for(var a=0;a<this.verFrets.length;a++)$("."+HOR_FRET_CLASS,$(this.verFrets[a])).last().remove()};Fretboard.prototype.onFretClick=function(a){a=a.data.that;var b=a.$fretboardBlock.find("."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS).index(this);if(a.state.boxFirstFret==b)a.state.boxFirstFret=-1;else{var c=a.calculateNotesBoxSizeForAllStrings(b);a.isBoxFit(b,c)&&(a.state.boxFirstFret=b)}a.putNotesOnAllStrings();a.state.saveToQuery()};
Fretboard.prototype.onFretHoverIn=function(a){var b=a.data.that;a=b.$fretboardBlock.find("."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS).index(this);var c=b.calculateNotesBoxSizeForAllStrings(a);if(b.isBoxFit(a,c))for(var b=$("."+FRET_HOVER_CLASS,b.$fretboardBlock),d=0;d<=c;d++){var e=FRET_HOVER_ACTIVE_CENTER_CLASS;0==d?e=FRET_HOVER_ACTIVE_START_CLASS:d==c&&(e=FRET_HOVER_ACTIVE_END_CLASS);$(b[a+d]).toggleClass(e,!0)}};
Fretboard.prototype.onFretHoverOut=function(a){a.data.that.$fretboardBlock.find("."+FRET_HOVER_CLASS).toggleClass(FRET_HOVER_ACTIVE_START_CLASS,!1).toggleClass(FRET_HOVER_ACTIVE_CENTER_CLASS,!1).toggleClass(FRET_HOVER_ACTIVE_END_CLASS,!1)};
Fretboard.prototype.init=function(){for(var a=0;a<FRETS_NUMBER;a++)this.$fretboardBlock.children().last().before(STRING_VER_FRET_TMPL());this.verFrets=$("."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS,this.$fretboardBlock);for(a=0;a<this.state.stringsNumber;a++)this.addString(a);this.$fretboardBlock.on("click","."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS,{that:this},this.onFretClick);this.$fretboardBlock.on("mouseenter","."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS,{that:this},this.onFretHoverIn);
this.$fretboardBlock.on("mouseleave","."+NULL_VER_FRET_CLASS+", ."+VER_FRET_INNER_CLASS,{that:this},this.onFretHoverOut)};function Neck(a,b,c,d,e,f,g){this.state=a;this.$neckBlock=b;this.$stringsNumberBlock=c;this.$addStringBtn=d;this.$delStringBtn=e;this.$tuningOptionsBlock=f;this.$lhToggleBlock=g;var l=this;this.fretboard=new Fretboard(a,$("."+FRETBOARD_CLASS,b));this.stringsTunings=new StringsTuning(a,$("."+STRINGS_OPTIONS_BLOCK_CLASS,b),function(a){l.putNotesOnString(a);l.fretboard.putNotesOnNearStrings(a);l.selectCurrentTuning()});this.init()}Neck.prototype.putNotesOnString=function(a){this.fretboard.putNotesOnString(a)};
Neck.prototype.putNotesOnAllStrings=function(){this.fretboard.putNotesOnAllStrings()};Neck.prototype.moveTuning=function(a){for(var b=0;b<this.state.stringsTunes.length;b++)this.state.stringsTunes[b]=Note.nextSemiTones(this.state.stringsTunes[b],a)};Neck.prototype.selectCurrentStringsTunes=function(){this.stringsTunings.selectCurrentStringsTunes()};
Neck.prototype.selectCurrentTuning=function(){this.$tuningOptionsBlock.find("."+TUNING_SELECT_CLASS+" [value='"+this.state.tuning+"']").prop("selected",!0)};Neck.prototype.switchLH=function(){this.$lhToggleBlock.find("."+TOGGLE_SLIDER_CLASS).toggleClass(SLIDER_LH_CLASS,this.state.isLH).toggleClass(SLIDER_RH_CLASS,!this.state.isLH);this.$neckBlock.toggleClass(LH_CLASS,this.state.isLH)};Neck.prototype.switchLHevent=function(){this.state.isLH=!this.state.isLH;this.switchLH();this.state.saveToQuery()};
Neck.prototype.onTuningChange=function(a){a=a.data.that;var b=$(this).val().toLowerCase();b==CUSTOM_TUNING_VALUE?a.state.tuning=b:Tuning.isCorrect(b)&&(a.state.tuning=b,a.state.stringsTunes=Tuning.getStringsTunes(b),a.moveTuning(a.state.halfStep),a.putNotesOnAllStrings(),a.selectCurrentStringsTunes());a.state.saveToQuery()};Neck.prototype.selectCurrentHalfStep=function(){$("."+HALF_STEP_SELECT_CLASS+" [value='"+this.state.halfStep+"']",this.$tuningOptionsBlock).prop("selected",!0)};
Neck.prototype.onHalfStepChange=function(a){a=a.data.that;var b=a.state.halfStep,c=$(this).val().replace(/[^-0-9]/gim,""),c=+c;a.state.halfStep=c;a.moveTuning(c-b);a.selectCurrentStringsTunes();a.putNotesOnAllStrings();a.state.saveToQuery()};Neck.prototype.onLeftArrowHalfStepClick=function(a){a=a.data.that;var b=a.state.halfStep;b!=-MAX_HALF_STEP&&(b=Halfstep.prev(b),a.state.halfStep=b,a.moveTuning(-1),a.selectCurrentStringsTunes(),a.putNotesOnAllStrings(),a.selectCurrentHalfStep(),a.state.saveToQuery())};
Neck.prototype.onRightArrowHalfStepCLick=function(a){a=a.data.that;var b=a.state.halfStep;b!=MAX_HALF_STEP&&(b=Halfstep.next(b),a.state.halfStep=b,a.moveTuning(1),a.selectCurrentStringsTunes(),a.putNotesOnAllStrings(),a.selectCurrentHalfStep(),a.state.saveToQuery())};
Neck.prototype.onAddStringButton=function(a){a=a.data.that;if(a.state.stringsNumber<MAX_STRINGS_NUMBER){a.fretboard.addString(a.state.stringsNumber);var b=Tuning.getStringTune(a.state.stringsTunes,a.state.stringsNumber);a.stringsTunings.addStringTuning(b);a.state.stringsNumber++;a.$stringsNumberBlock.text(""+a.state.stringsNumber);a.state.saveToQuery()}};
Neck.prototype.onDelStringButton=function(a){a=a.data.that;a.state.stringsNumber>MIN_STRINGS_NUMBER&&(a.fretboard.delLastString(),a.stringsTunings.delLastString(),a.state.stringsNumber--,a.$stringsNumberBlock.text(""+a.state.stringsNumber),a.state.saveToQuery())};Neck.prototype.onLhToggleSlider=function(a){a.data.that.switchLHevent()};Neck.prototype.onLhToggleClick=function(a){a=a.data.that;a.state.isLH||a.switchLHevent()};Neck.prototype.onRhToggleClick=function(a){a=a.data.that;a.state.isLH&&a.switchLHevent()};
Neck.prototype.init=function(){this.$stringsNumberBlock.text(""+this.state.stringsNumber);this.selectCurrentTuning();this.selectCurrentHalfStep();this.putNotesOnAllStrings();this.switchLH();this.$addStringBtn.click({that:this},this.onAddStringButton);this.$delStringBtn.click({that:this},this.onDelStringButton);$("."+TUNING_SELECT_CLASS,this.$tuningOptionsBlock).change({that:this},this.onTuningChange);$("."+HALF_STEP_SELECT_CLASS,this.$tuningOptionsBlock).change({that:this},this.onHalfStepChange);
this.$tuningOptionsBlock.find("."+HALF_STEP_BLOCK_CLASS).find("."+LEFT_ARROW_CLASS).click({that:this},this.onLeftArrowHalfStepClick);this.$tuningOptionsBlock.find("."+HALF_STEP_BLOCK_CLASS).find("."+RIGHT_ARROW_CLASS).click({that:this},this.onRightArrowHalfStepCLick);this.$lhToggleBlock.find("."+TOGGLE_CHECKBOX_CLASS).click({that:this},this.onLhToggleSlider);this.$lhToggleBlock.find("."+LH_TOGGLE_CLASS).click({that:this},this.onLhToggleClick);this.$lhToggleBlock.find("."+RH_TOGGLE_CLASS).click({that:this},
this.onRhToggleClick)};function ScalesItemState(a,b){this.id=a;this.type="scales";this.scale="major";this.root="C";this.scaleNotes=DEFAULT_SCALE_NOTES;this.semiTones=DEFAULT_SCALE_SEMITONES;this.tuning="standart_e";this.stringsNumber=0;this.stringsTunes=DEFAULT_STRING_TUNES;this.halfStep=0;this.isTriadMode=!1;this.boxFirstFret=-1;this.normalNotesShowPattern=DEFAULT_NOTES_SHOW_PATTERN;this.triadsNotesShowPattern=DEFAULT_TRIADS_SHOW_PATTERN;this.isLH=!1;this.init(b)}
ScalesItemState.prototype.saveToQuery=function(){menuItems.updateItemSerializedData(this.id,this.serialize());menuItems.updateItemsQueryParams()};ScalesItemState.prototype.serialize=function(){var a=[this.type,this.scale,this.root,this.tuning,this.halfStep,this.stringsNumber,this.stringsTunes,this.isTriadMode,this.normalNotesShowPattern.slice(),this.triadsNotesShowPattern.slice(),this.boxFirstFret,this.isLH];return JSON.stringify(a,ParsingUt.semiTonesPatternBoolToInt)};
ScalesItemState.prototype.deserialize=function(a){a=JSON.parse(a,ParsingUt.semiTonesPatternIntToBool);this.type=a[0];this.scale=a[1];this.root=a[2];this.tuning=a[3];this.halfStep=a[4];this.stringsNumber=a[5];this.stringsTunes=a[6];this.isTriadMode=a[7];this.normalNotesShowPattern=a[8];this.triadsNotesShowPattern=a[9];this.semiTones=Scale.getSemitones(this.scale);this.scaleNotes=Note.getNotesFromSemiTones(this.root,this.semiTones);this.boxFirstFret=a[10];this.isLH=a[11]};
ScalesItemState.prototype.saveToDefaultOptions=function(){defaults.scales.scale=this.scale;defaults.scales.root=this.root;defaults.scales.semiTones=this.semiTones;defaults.scales.tuning=this.tuning;defaults.scales.halfStep=this.halfStep;defaults.scales.stringsTunes=this.stringsTunes;defaults.scales.stringsNumber=this.stringsNumber;defaults.scales.isTriadMode=this.isTriadMode;defaults.scales.boxFirstFret=this.boxFirstFret;defaults.scales.isLH=this.isLH;defaults.scales.saveToCookie()};
ScalesItemState.prototype.readFromDefaultOptions=function(){this.scale=defaults.scales.scale;this.root=defaults.scales.root;this.semiTones=Scale.getSemitones(this.scale);this.scaleNotes=Note.getNotesFromSemiTones(this.root,this.semiTones);this.tuning=defaults.scales.tuning;this.halfStep=defaults.scales.halfStep;this.stringsTunes=defaults.scales.stringsTunes;this.stringsNumber=defaults.scales.stringsNumber;this.isTriadMode=defaults.scales.isTriadMode;this.normalNotesShowPattern=defaults.scales.normalNotesShowPattern;
this.triadsNotesShowPattern=defaults.scales.triadsNotesShowPattern;this.boxFirstFret=defaults.scales.boxFirstFret;this.isLH=defaults.scales.isLH};ScalesItemState.prototype.init=function(a){this.readFromDefaultOptions();a&&this.deserialize(a);this.saveToQuery()};function ScalesItem(a,b){this.state=new ScalesItemState(a,b);this.$itemBlock=$("#"+a);this.init()}ScalesItem.prototype.putNotesOnAllStrings=function(){this.neck.putNotesOnAllStrings()};ScalesItem.prototype.selectCurrentStringsTunes=function(){this.neck.selectCurrentStringsTunes()};ScalesItem.prototype.selectCurrentScale=function(){$("."+SCALE_SELECT_CLASS+" [value='"+this.state.scale+"']",this.$itemBlock).prop("selected",!0)};
ScalesItem.prototype.updateScaleNotesBlock=function(){$("."+SCALE_NOTES_CLASS,this.$itemBlock).remove();var a=this.state.scaleNotes.slice();a.push(this.state.root);a={root:this.state.root,semiTones:this.state.semiTones,notes:a};$("."+SCALE_NOTES_BLOCK_CLASS,this.$itemBlock).append(SCALE_NOTES_TMPL(a));var a=$("."+SCALE_NOTES_CLASS,this.$itemBlock).find("."+SCALE_NOTE_TEXT_CLASS),b=a.length-1,c=this.state.normalNotesShowPattern;this.state.isTriadMode&&(c=this.state.triadsNotesShowPattern);for(var d=
0;d<b;d++)if(!c[d]){var e=$(a[d]);e.toggleClass(TRANSPARENT_BLOCK_CLASS,!0);0==d&&(e=$(a[b]),e.toggleClass(TRANSPARENT_BLOCK_CLASS,!0))}$("."+SCALE_NOTES_CLASS,this.$itemBlock).on("click","."+SCALE_NOTE_CLASS,{that:this},this.onScaleNoteClick)};
ScalesItem.prototype.selectCurrentRootNote=function(){$("."+ROOT_NOTE_CLASS+"."+SELECTED_TEXT_CLASS,this.$itemBlock).toggleClass(SELECTED_TEXT_CLASS,!1);$("."+ROOT_NOTE_CLASS+":contains('"+this.state.root+"')",this.$itemBlock).first().toggleClass(SELECTED_TEXT_CLASS,!0)};
ScalesItem.prototype.onScaleChange=function(a){a=a.data.that;var b=$(this).val().toLowerCase();Scale.isCorrect(b)&&(a.state.scale=b,a.state.semiTones=Scale.getSemitones(b),a.state.scaleNotes=Note.getNotesFromSemiTones(a.state.root,a.state.semiTones),a.putNotesOnAllStrings(),a.updateScaleNotesBlock(),a.state.saveToQuery())};
ScalesItem.prototype.onRootNoteChange=function(a){a=a.data.that;var b=$(this).text();Note.isCorrect(b)&&(a.state.root=b.toUpperCase(),a.selectCurrentRootNote(),a.state.scaleNotes=Note.getNotesFromSemiTones(a.state.root,a.state.semiTones),a.updateScaleNotesBlock(),a.putNotesOnAllStrings(),a.state.saveToQuery())};
ScalesItem.prototype.onScaleNoteClick=function(a){a=a.data.that;var b=$("."+SCALE_NOTE_CLASS,a.$itemBlock).index(this),b=b%a.state.scaleNotes.length,c;a.state.isTriadMode?(c=!a.state.triadsNotesShowPattern[b],a.state.triadsNotesShowPattern[b]=c):(c=!a.state.normalNotesShowPattern[b],a.state.normalNotesShowPattern[b]=c);0==b?(b=$("."+SCALE_NOTE_CLASS,a.$itemBlock).last().find("."+SCALE_NOTE_TEXT_CLASS),b.toggleClass(TRANSPARENT_BLOCK_CLASS,!c),b=$("."+SCALE_NOTE_CLASS,a.$itemBlock).first().find("."+
SCALE_NOTE_TEXT_CLASS)):b=$(this).find("."+SCALE_NOTE_TEXT_CLASS);b.toggleClass(TRANSPARENT_BLOCK_CLASS,!c);a.putNotesOnAllStrings();a.state.saveToQuery()};ScalesItem.prototype.onTriadsCheckboxClick=function(a){a=a.data.that;a.state.isTriadMode?(a.state.isTriadMode=!1,a.$triadsCheckbox.hide(),a.$triadsCheckboxEmpty.show()):(a.state.isTriadMode=!0,a.$triadsCheckboxEmpty.hide(),a.$triadsCheckbox.show());a.updateScaleNotesBlock();a.putNotesOnAllStrings();a.state.saveToQuery()};
ScalesItem.prototype.initTriadsCheckbox=function(){this.$triadsCheckbox=$("."+TRIADS_CHECKBOX_CLASS,this.$itemBlock);this.$triadsCheckboxEmpty=$("."+TRIADS_CHECKBOX_EMPTY_CLASS,this.$itemBlock);this.state.isTriadMode?this.$triadsCheckboxEmpty.hide():this.$triadsCheckbox.hide();this.$triadsCheckbox.click({that:this},this.onTriadsCheckboxClick);this.$triadsCheckboxEmpty.click({that:this},this.onTriadsCheckboxClick)};
ScalesItem.prototype.initDOM=function(){this.$itemOptionsBlock=$("."+ITEM_OPTIONS_BLOCK,this.$itemBlock);this.$stringsBtnsBlock=$(STRINGS_BTNS_BLOCK_TMPL()).insertBefore($("."+ITEM_HEAD_SELECT_CLASS,this.$itemBlock));this.$lhToggleBlock=$(LH_TOGGLE_BLOCK_TMPL()).insertAfter($("."+ITEM_HEAD_SELECT_CLASS,this.$itemBlock));this.$neckBlock=$(NECK_BLOCK_TMPL()).insertAfter($("."+ITEM_HEAD_CLASS,this.$itemBlock));this.$scalesOptionsBlock=$(SCALES_OPTIONS_BLOCK_TMPL()).prependTo(this.$itemOptionsBlock);
this.$scalesSelectBlock=$(SCALES_SELECT_BLOCK_TMPL()).prependTo(this.$itemOptionsBlock);this.$TuningOptionsBlock=$(TUNING_OPTIONS_BLOCK_TMPL()).prependTo(this.$itemOptionsBlock)};
ScalesItem.prototype.init=function(){this.initDOM();this.neck=new Neck(this.state,this.$neckBlock,$("."+STRING_NUMBER_CLASS,this.$itemBlock),$("."+ADD_STRING_BTN_CLASS,this.$itemBlock),$("."+DEL_STRING_BTN_CLASS,this.$itemBlock),$("."+TUNING_OPTIONS_CLASS,this.$itemBlock),this.$lhToggleBlock);this.initTriadsCheckbox();this.updateScaleNotesBlock();this.selectCurrentScale();this.selectCurrentRootNote();$("."+SCALE_SELECT_CLASS,this.$itemBlock).change({that:this},this.onScaleChange);$("."+SCALE_NOTES_BLOCK_CLASS,
this.$itemBlock).on("click","."+ROOT_NOTE_CLASS,{that:this},this.onRootNoteChange)};itemsFactory={getItem:function(a,b){var c;c=[];var d=SCALES_TYPE;if(b)try{c=JSON.parse(b,ParsingUt.semiTonesPatternIntToBool),d=c[0]}catch(e){console.log(e)}switch(d){case SCALES_TYPE:c=new ScalesItem(a,b);break;case CHORDS_TYPE:c=new ChordsItem(a,b);break;default:c=new ScalesItem(a,b),console.log(WRONG_ITEM_TYPE_MSG+" "+d)}return c}};var menuItems={itemsNumber:0,items:{},itemsSerializedStates:{},getIDforNewItem:function(){for(var a=0;void 0!==this.items[ITEMS_ID_BASE+a];)a++;return ITEMS_ID_BASE+a},deleteItem:function(a){this.itemsNumber==MAX_ITEMS_NUMBER&&this.$addNewItemBtn.show(200);delete this.items[a]&&(delete this.itemsSerializedStates[a],this.updateItemsQueryParams(),this.itemsNumber--)},updateItemsQueryParams:function(){for(var a="?",b=0;b<MAX_ITEMS_NUMBER;b++){var c=ITEMS_ID_BASE+b;void 0!==this.itemsSerializedStates[c]&&
(c=btoa(this.itemsSerializedStates[c].getJSON()),a+="i"+b+"="+c,b<this.itemsNumber&&(a+="&"))}history.replaceState({},"",a)},updateItemSerializedData:function(a,b){this.itemsSerializedStates[a]||(this.itemsSerializedStates[a]=new ItemSerializedState(b));this.itemsSerializedStates[a].setJSON(b)},createNewItem:function(){var a=this.getIDforNewItem();this.itemsNumber<MAX_ITEMS_NUMBER?(this.items[a]=new ItemBase(a),this.itemsNumber++):this.$addNewItemBtn.hide(200)},createItemsFromQueryParams:function(a){for(var b=
0;b<a.length&&b<MAX_ITEMS_NUMBER;b++){var c=this.getIDforNewItem();this.items[c]=new ItemBase(c,a[b].getJSON());this.itemsNumber++}this.itemsNumber>=MAX_ITEMS_NUMBER&&this.$addNewItemBtn.hide(200)},readItemsQueryParams:function(){var a=window.location.href,b=a.indexOf("?"),c=[];if(-1!=b)for(var a=a.slice(b+1).split("&"),d=0;d<a.length&&d<MAX_ITEMS_NUMBER;d++)if(b=a[d].indexOf("="),-1!=b){b=a[d].slice(b+1);b=decodeURI(b);try{b=atob(b),c.push(new ItemSerializedState(b))}catch(e){console.log(PARAMS_ATOB_ERROR_MSG+
"\n"+e)}}return c},onNewItemButton:function(a){that=a.data.that;that.createNewItem()},init:function(){this.$addNewItemBtn=$("#"+ADD_NEW_ITEM_BTN_ID);this.$addNewItemBtn.click({that:this},this.onNewItemButton);var a=this.readItemsQueryParams();0==a.length?this.createNewItem():this.createItemsFromQueryParams(a)}};function ItemSerializedState(a){this.JSON=a;this.validateJSON()}ItemSerializedState.prototype.getJSON=function(){return this.JSON};ItemSerializedState.prototype.setJSON=function(a){this.JSON=a;this.validateJSON()};ItemSerializedState.prototype.getItemType=function(){var a="";try{a=JSON.parse(this.JSON,ParsingUt.semiTonesPatternIntToBool)[0]}catch(b){}return a};
ItemSerializedState.prototype.scalesStateValidate=function(){var a=[];try{a=JSON.parse(this.JSON,ParsingUt.semiTonesPatternIntToBool)}catch(c){}var b=!0;a[0]=SCALES_TYPE;12!=a.length&&(b=!1);Scale.isCorrect(a[1])||(b=!1,a[1]=defaults.scales.scale);Note.isCorrect(a[2])||(b=!1,a[2]=defaults.scales.root);Tuning.isCorrect(a[3])||(b=!1,a[3]=defaults.scales.tuning);Halfstep.isCorrect(a[4])||(b=!1,a[4]=defaults.scales.halfStep);ParsingUt.isCorrectStringsNumber(a[5])||(b=!1,a[5]=defaults.scales.stringsNumber);
Tuning.isCorrectNotes(a[6])||(b=!1,a[6]=defaults.scales.stringsTunes);"boolean"!==typeof a[7]&&(b=!1,a[7]=defaults.scales.isTriadMode);ParsingUt.isCorrectNotesShowPattern(a[8])||(b=!1,a[8]=defaults.scales.normalNotesShowPattern);ParsingUt.isCorrectNotesShowPattern(a[9])||(b=!1,a[9]=defaults.scales.triadsNotesShowPattern);ParsingUt.isCorrectBoxFret(a[10])||(b=!1,a[10]=defaults.scales.boxFirstFret);"boolean"!==typeof a[11]&&(b=!1,a[11]=defaults.scales.isLH);b||(this.JSON=JSON.stringify(a,ParsingUt.semiTonesPatternBoolToInt))};
ItemSerializedState.prototype.validateJSON=function(){switch(this.getItemType()){case SCALES_TYPE:this.scalesStateValidate();break;case CHORDS_TYPE:this.chordsStateValidate();break;default:this.scalesStateValidate()}};metronome.init();commonSettings.init();defaults.init();menuItems.init();
